- converter/COLLADA2GLTF/COLLADA2GLTFWriter.cpp
Compilation was failing on Windows because it didn't know about the type String. Added COLLADAFW:: and all is good again.
> Fixed compilation error.

- converter/COLLADA2GLTF/shaders/commonProfileShaders.cpp
Fixed issue where if the cwd isn't a models directory the parent path gets prepended to the texture data uri. This causes the png data to not be read and we set the blending flag incorrectly.
> Images weren't be checked for transparency

- converter/COLLADA2GLTF/COLLADA2GLTFWriter.cpp
When we try to embed images with spaces we don't decode the URI so the %20's are in the path and we fail to find it. This change decodes the path before we try to open it.
> Image files with spaces don't embed correctly.

- converter/COLLADA2GLTF/GLTF/GLTFAsset.cpp
- converter/COLLADA2GLTF/shaders/commonProfileShaders.cpp
@pjcozzi I checked the generated file it looks fine - but I can't test the viewer right now. Can you check with Cesium before merging ? 
The generated technique hashcode wasn't taking into account the vertex attributes - which was quite wrong, and possibly a regression.
Note: for the shader that only contains one position, the generated code is quite dumb and could be much better but we can track that separately. For now the scope of this fix was make sure we generate a shader consistent with the vertex attributes.
> https://github.com/KhronosGroup/glTF/issues/369

- converter/COLLADA2GLTF/COLLADA2GLTFWriter.cpp
- converter/COLLADA2GLTF/helpers/geometryHelpers.cpp
Fixes crashes caused by
1. Animations that don't target nodes (such as animation targeting the diffuse color of an effect)
2. Empty source arrays. Not sure why this keeps coming up by I've seen multiple models that have an `<source>` element used for normals. Regardless we shouldn't crash.
> Fixed a few random crashes

- converter/COLLADA2GLTF/main.cpp
This fixes some issues with the built-in help text.
* The number of help options is now automatically computed, so none are left off the end.
* The `-a` option help text is commented out, to match code supporting the option which is also currently commented out.
* The `-e` option has an improved description, revealed now by the above fix.
Fixes #310.
> Fix help text

- converter/COLLADA2GLTF/GLTF/GLTFAsset.cpp
- converter/COLLADA2GLTF/GLTF/GLTFAsset.h
- converter/COLLADA2GLTF/GLTF/GLTFWriter.cpp
- converter/COLLADA2GLTF/GLTF/GLTFWriter.h
Made GLTFWriter abstract and made the previous implementation the default in GLTFDefaultWriter. This will allow people to implement their own writers (minified, better double precision, output to string, etc).
> Added a plugin point for the writer object

- converter/COLLADA2GLTF/GLTF/GLTFAsset.cpp
For some reason the include of `GLTFOpenCOLLADAUtils.h` was inside `#if __cplusplus <= 199711L`. I don't have a linux machine but I'm assuming this is the fix for the linux compile issue mentioned by @JHanley85 in #385.
> Fixed linux build.

- specification/README.md
The new MIME type is meant to fit in with the official list of [MIME types for models](http://www.iana.org/assignments/media-types/media-types.xhtml#model).  It also makes use of the [`+json` suffix](https://tools.ietf.org/html/rfc6839#page-4) indicating the format of the data.
I've removed the old "assetLayout" graphic as it has the obsolete `.json` extension burned into it, and the information there was redundant with what's written directly above it in the same README.
Are there any other places where the official MIME type & extension can or should be specified outside of this README?
/cc @shunter
> Specify MIME types for transfer to client.

- specification/README.md
@tparisi this is a PR into `spec-1.0`.
Using "```javascript" allows us to put comments in the examples, which is not valid JSON, but is handy.
This also fixes white spaces.
> Make JSON examples consistent

- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
- COLLADA2GLTF/GLTF/GLTFTypesAndConstants.h
The converter was never fixed to make this a string.
> Changed asset.version to be a string as per the 1.0 spec.

- specification/schema/accessor.schema.json
- specification/schema/bufferView.schema.json
- specification/schema/mesh.primitive.schema.json
- specification/schema/sampler.schema.json
- specification/schema/shader.schema.json
- specification/schema/technique.parameters.schema.json
- specification/schema/technique.states.functions.schema.json
- specification/schema/technique.states.schema.json
- specification/schema/texture.schema.json
This is intended to make the enum names more machine parsable for our ongoing C# code-gen work.
> Pull the data about integer enum names from the detailed description into a new property.

- extensions/Khronos/KHR_materials_common/README.md
(originally here: https://github.com/KhronosGroup/glTF/pull/506)
> KHR_materials_common: Two sentences and example for naming of mesh attributes

- extensions/Khronos/KHR_materials_common/README.md
As discussed [here](https://github.com/AnalyticalGraphicsInc/cesium/pull/3294#issuecomment-163057175), this PR adapts the spec to clarify handling of different values for the specular exponent.
Just a strawman proposal - it would probably also be a good solution to leave this special case of adapting values from [0,1] completely out. I guess that could facilitate writing correct reader / renderer implementations even more.
> Common material spec: handling of specular exponent

- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
We didn't check whether transparent was a color or texture and we just use the alpha value which was in its initial state of -1. This caused meshes to be transparent when they weren't suppose to be. The real fix would be to handle a transparency map, but that is a decent undertaking. This fix ignores the transparent texture like before, it just doesn't introduce a -1 into the equation.
Its a band aid for #530
> Fixes blank textures

- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
- COLLADA2GLTF/helpers/mathHelpers.cpp
prevent a uniform scaling of zero from causing invalid values to be returned from a matrix decompose
> Uniform scaling of zero fix

- specification/README.md
Changed "primitive": 4 to "mode": 4 in the examples.
Also fixed the anchor for "Accessing Binary Data" in the table of contents.
> Fixed primitive.mode in the spec

- COLLADA2GLTF/CMakeLists.txt
- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
- COLLADA2GLTF/GLTF/GLTFAccessor.cpp
- COLLADA2GLTF/GLTF/GLTFAnimation.cpp
- COLLADA2GLTF/GLTF/GLTFAsset.cpp
- COLLADA2GLTF/GLTF/GLTFBuffer.cpp
- COLLADA2GLTF/GLTF/GLTFConfig.cpp
- COLLADA2GLTF/GLTF/GLTFDefaultWriter.cpp
- COLLADA2GLTF/GLTF/GLTFDefaultWriter.h
- COLLADA2GLTF/GLTF/GLTFEffect.cpp
- COLLADA2GLTF/GLTF/GLTFExtras.cpp
- COLLADA2GLTF/GLTF/GLTFMesh.cpp
- COLLADA2GLTF/GLTF/GLTFPrimitive.cpp
- COLLADA2GLTF/GLTF/GLTFSkin.cpp
- COLLADA2GLTF/GLTF/GLTFWriter.cpp
- COLLADA2GLTF/GLTF/GLTFWriter.h
- COLLADA2GLTF/JSON/JSONNumber.cpp
- COLLADA2GLTF/JSON/JSONValue.cpp
- COLLADA2GLTF/assetModifiers/GLTFFlipUVModifier.cpp
- COLLADA2GLTF/convert/animationConverter.cpp
- COLLADA2GLTF/convert/meshConverter.cpp
- COLLADA2GLTF/extensions/o3dgc-compression/GLTF-Open3DGC.cpp
- COLLADA2GLTF/helpers/encodingHelpers.cpp
- COLLADA2GLTF/helpers/geometryHelpers.cpp
- COLLADA2GLTF/helpers/mathHelpers.cpp
- COLLADA2GLTF/main.cpp
Removed rapidjson from all public headers. Its now only used for reading the json and as the default writer. This allows us to use a different version or other json library if we specify a custom writer from our own app.
> Removed requirement of rapidjson

- COLLADA2GLTF/shaders/commonProfileShaders.cpp
Part of the fixes for #556.
Tested with the vc model and the output looks correct 
[vc.zip](https://github.com/KhronosGroup/glTF/files/226135/vc.zip)
> Depth mask should be written as an array

- COLLADA2GLTF/GLTF/GLTFAsset.cpp
- COLLADA2GLTF/GLTF/GLTFPrimitive.cpp
- COLLADA2GLTF/GLTF/GLTFPrimitive.h
In reference to #556.
The TEXCOORD field is unnecessary unless the material for the node references a texture.
I've tested this with the box model and it successfully removed unused TEXCOORD fields. I've also tested it with the milk truck model and it correctly identifies that the TEXCOORD fields are used and doesn't remove them.
Also adds the ```removeVertexAttributes``` method to GLTFPrimitive.
Edit: After reviewing a bit, I realized that this still leaves the unused accessor and data for TEXCOORD. While that doesn't break anything, they should be removed to reduce the size of the model. Feel free to comment on what's here already, and I should have a fix in for the aforementioned soon.
> Remove TEXCOORD vertexAttribute when it is unnecessary

- specification/README.md
The ordering of parameters for blendFuncSeparate are incorrect.  See http://docs.gl/es2/glBlendFuncSeparate
Also removed the unused lighting section from the Table of Contents.
> Fixed default values for blendFuncSeparate.

- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
Thanks to @gbeatty for pointing this out.
If a COLLADA model uses instance_geometry it should create new meshes along with the nodes so that material binding can be different.
See the attached zip [convertedModels.zip](https://github.com/KhronosGroup/glTF/files/271165/convertedModels.zip)
The COLLADA file currently produces the incorrect output in 1m_cube.gltf. With these changes it produces 1m_cube_fixed.gltf which displays the correct behavior of having different materials on each side.
> Create unique mesh instances for collada models with instance geometry

- extensions/Khronos/KHR_binary_glTF/README.md
I consider this a clarification - not a breaking change that would require a new version - since if `sceneLength === 0`, then the binary glTF payload would not contain a glTF asset.
@tparisi @mlimper @lexaknyazev do you agree?
> Clarify that sceneLength in KHR_binary_glTF must be greater than zero

- specification/README.md
- specification/schema/mesh.primitive.schema.json
Part of #563
>  There is no explicit requirement on the mesh.primitive.indices accessor to not to be FLOAT and to reference bufferView with ELEMENT_ARRAY_BUFFER target.
@lexaknyazev what do you think of this word?
Also, I think this is fine for the 1.0 spec since these are the constraints that are needed in practice; this is just a clarification and does not need to wait for 1.0.1
> Make indices accessor constraints explicit

- extensions/Vendor/WEB3D_quantized_attributes/README.md
> 'Three' should be 'Two'

- specification/README.md
- specification/schema/accessor.schema.json
- specification/schema/examples/glExtensionsUsed.json
- specification/schema/examples/webglExtensionsUsed.json
- specification/schema/glTF.schema.json
PR into `1.0.1` branch for #570.
Adds `webglExtensionsUsed` property and `5125` (UNSIGNED_INT) `accessor.componentType` value.
For example:
```json
{
"webglExtensionsUsed " : ["OES_element_index_uint"],
"accessor_id": {
"bufferView": "bufferView_id",
"byteOffset": 0,
"byteStride": 0,
"componentType": 5125,
"count": 36,
"type": "SCALAR"
}
}
```
> Draft of uint32 support

- specification/README.md
- specification/schema/accessor.schema.json
I've put it in accessor's definitions, because it's the only case of direct comparison between buffer-stored and json-stored floats.
> Clarification on min/max float precision

- COLLADA2GLTF/GLTF/GLTFAsset.cpp
Fixes #635. CesiumMan converts correctly after this change and CesiumMilkTruck still has its unused TEXCOORD fields removed.
If you look at the collada between these two models the issue is that in CesiumMilkTruck, the texture is bound to a texture coordinate set:
```xml
<diffuse>
<texture texture="Image0001-sampler" texcoord="Texture" />
</diffuse>
```
while in CesiumMan, it is not:
```xml
<diffuse>
<texture texture="Cesium_Man_jpg-sampler"/>
</diffuse>
```
The TEXCOORD removal optimization now jumps ship if a texture is unbound since there's no way to tell what is used and what isn't.
> Check for unbound textures

- specification/README.md
- specification/schema/node.schema.json
- specification/schema/skin.schema.json
> Skinning fixes for 1.0.1

- COLLADA2GLTF/JSON/JSONNumber.cpp
- COLLADA2GLTF/helpers/geometryHelpers.cpp
This solves the build issue on Linux (I had it on latest Arch, @timknip on Ubuntu)
> Fill in missing includes #656

- README.md
All JglTF libraries are still work in progress, but some of them might already be interesting for others.
> Added links to Java glTF libraries

- COLLADA2GLTF/profiles/webgl-1.0/GLTFWebGL_1_0_Profile.cpp
- specification/README.md
- specification/schema/asset.profile.schema.json
> Drop revision number from profile.version

- COLLADA2GLTF/GLTF/GLTF.h
I get a few compile errors about missing `memcpy` and `memcmp`.
> Fixed compile issue when linking into another exe

- specification/README.md
- specification/schema/glTF.schema.json
See https://github.com/KhronosGroup/glTF/issues/695#issuecomment-246133871
> extensionsRequired property

- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
@tfili This should fix the model converter issues we were having
> Overwrite node OID when it is an empty string

- COLLADA2GLTF/COLLADA2GLTFWriter.cpp
@tfili This should solve our problem with the attached conditioned CesiumMan collada file
[Model.zip](https://github.com/KhronosGroup/glTF/files/498692/Model.zip)
> Translation animations now include node translation if only a single axis is specified

- specification/README.md
- specification/schema/examples/techniques.json
- specification/schema/technique.states.functions.schema.json
The ordering was incorrect in this area. Uncovered through this post on the Cesium forum: https://groups.google.com/forum/#!msg/cesium-dev/BP_fs8K19ww/n2SBwzEsBAAJ
> Fixed ordering of blendFuncSeparate

- README.md
xeoEngine was recently renamed to "xeogl", so this change fixes the links to glTF examples for that framework.
> Updated example links

- README.md
Add link to `gltf-model` component, and to A-Frame homepage.
> Update links for A-Frame glTF loader.

- README.md
Finally completed the article, so I will pull the request.
I will maintain this article for a long time. It will be the best resource for Japanese-speaking people to learn glTF.
(I will also write articles about glTF skinning animation (using raw WebGL) in the future as well.)
If there is no problem, please merge.
> Add the link to Japanese introduction post of glTF

- extensions/Vendor/CESIUM_binary_glTF/README.md
I assume EXT should now be KHR? The current link is broken, if not.
> Link to current (KHR) binary extension spec.

- README.md
Add my tag-based Web3D library(Grimoire.js) to the list on README.md.
My WebGL library (Grimoire.js(https://github.com/GrimoireGL/GrimoireJS)) supports glTF 1.0 completely.(See https://github.com/cx20/gltf-test)
I haven't add English document on official site(https://grimoire.gl). But, it will be fully translated into English soon and it will contains some glTF samples also.
Could be my libraries added to the list?
> Add Grimoire.js as Javascript library supporting glTF

- specification/2.0/README.md
- Emission to Emissive
- Removed epsilon from BRDF input equations
- Fixed capitalization / formatting
> Fix minor wording

- specification/2.0/README.md
Accessors are used not only for attributes, so language was changed to not use the term "attribute" in accessor definition. This also allows listing UNSIGNED_INT in a table with accessor component sizes.
CC @pjcozzi
> Refine accessor definition

- README.md
The `gltf-model` component was merged into the A-Frame library as of 0.5.0, and the external component is no longer maintained.
> Update link to A-Frame glTF loader.

- specification/2.0/README.md
- specification/2.0/schema/material.pbrMetallicRoughness.schema.json
- specification/2.0/schema/material.schema.json
Adding details on alpha coverage as per #822 
Also added doubleSided property from common materials extension to core spec since it can be used across multiple material models.
Doc: https://github.com/sbtron/glTF/tree/2.0Transparency/specification/2.0#alpha-coverage
Schemas:
https://github.com/sbtron/glTF/blob/2.0Transparency/specification/2.0/schema/material.schema.json
https://github.com/sbtron/glTF/blob/2.0Transparency/specification/2.0/schema/material.pbrMetallicRoughness.schema.json 
@AurL @cedricpinson could you review and ensure this meets your needs so you no longer have to use the extras field.
> Add alpha coverage details

- specification/2.0/README.md
- specification/2.0/schema/node.schema.json
See #878.
I've also changed semantic to plural form to indicate that each attribute value contains not just one joint but an array. Same with weights.
> Rename JOINT -> JOINTS_0

- specification/2.0/README.md
- specification/2.0/schema/mesh.primitive.attribute.schema.json
- specification/2.0/schema/mesh.primitive.schema.json
- specification/2.0/schema/mesh.primitive.target.schema.json
Fix #927, remove indirection.
@bghgary 
Should we require that `attributes` isn't empty? It's possible with `"minProperties": 1` schema rule. Same question about elements of the `targets` array.
> Fix primitive.targets, remove unneeded schema indirection

- specification/2.0/README.md
@lexaknyazev I wrote this part wrong originally. JOINTS_0 and WEIGHTS_0 are strictly for skinned animations and not morph targets.
> Fix description of JOINTS_0 and WEIGHTS_0 in mesh attribute table

- specification/2.0/schema/material.pbrMetallicRoughness.schema.json
- specification/2.0/schema/material.schema.json
Copied this note from the `emissiveFactor` to the other factors:
>  If an emissiveTexture is specified, this value is multiplied with the texel values.
Feel free to edit the wording.
> Add note to the pbrMetallicRoughness schema

- specification/2.0/README.md
- specification/2.0/schema/bufferView.schema.json
- specification/2.0/schema/mesh.primitive.schema.json
No syntax or semantic changes, just more verbose description.
> Clarify byteStride restrictions

- specification/2.0/README.md
We need to disallow `NaN`, `+Infinity`, and `-Infinity` in binary data, because JSON doesn't support these values (think `accessor.min/max`).
> Tightening float values

- specification/2.0/schema/animation.sampler.schema.json
- specification/2.0/schema/material.schema.json
Wetzel can handle this now as of AnalyticalGraphicsInc/wetzel#18.
---
Current version:
Interpolation algorithm. When an animation targets a node's rotation, and the animation's interpolation is `"LINEAR"`, spherical linear interpolation (slerp) should be used to interpolate quaternions. When interpolation is `"STEP"`, animated value remains constant to the value of the first point of the timeframe, until the next timeframe. When interpolation is `"CATMULLROMSPLINE"`, the animation's interpolation is computed using a uniform Catmull-Rom spline. When interpolation is `"CUBICSPLINE"`, the animation's interpolation is computed using a cubic spline with specified tangents. For each input value, the output stores three values: in-tangent, spline vertex, and out-tangent.
* **Type**: `string`
* …
> Move enum long descriptions to per-value fields.

- specification/2.0/README.md
- specification/2.0/schema/accessor.schema.json
From https://github.com/KhronosGroup/glTF-Sample-Models/issues/63.
CC @javagl
> Generalize accessor.min/max data type restrictions.

- specification/2.0/README.md
@lexaknyazev I hope this is right: The limit in GL 1.0 implies 
- 8 morph targets with *one* attribute **OR**
- 4 morph targets with *two* attributes **OR**
- 2 morph targets with *three* attributes
Also, someone please drop a note to the one who advocated for an unlimited number of morph targets (I'm not sure who it was)
> Added implementation note about morph target counts

- specification/2.0/schema/node.schema.json
Sadly, we can't check quaternion's length with schema, but it's still better than nothing.
> Soft enforcement of unit quaternions for node.rotation

- specification/2.0/README.md
As requested in https://github.com/KhronosGroup/glTF/pull/971#issuecomment-304392357
> Add implementation note for negative transform determinant

- specification/2.0/README.md
Split normative/non-normative parts of URIs section, disallow empty URIs in schema.
> Small edits of URIs section

- README.md
- extensions/Khronos/KHR_binary_glTF/README.md
- extensions/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
- extensions/README.md
- specification/README.md
1) Fix link to 2.0 spec on landing page
2) Move overview image from landing page to spec links page since its 1.0 specific
3) Update extension registry and fix links to individual extension specs
4) Mark specgloss extension as complete
5) Add note to binary extension that it is only needed in gltf 1.0
> Cleanup links for gltf 2.0

- specification/2.0/schema/camera.orthographic.schema.json
We can't disallow such case with schema, but it's worth noting.
> Add note about zero xmag/ymag

- specification/2.0/README.md
From [Specifying Extensions](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#specifying-extensions):
> All extensions used in a glTF asset must be listed in the top-level `extensionsUsed` array object...
> All glTF extensions required to load and/or render an asset must be listed in the top-level `extensionsRequired` array...
That implies, that all required extensions must also be listed in `extensionsUsed` array. However, schema allows `extensionsRequired` without `extensionsUsed`. This PR aligns schema with spec. 
@bghgary Please check whether such update is possible.
> Enforce extension lists dependency

- README.md
With the 1.1 release of blendergltf, glTF 2.0 output is now supported.
> Update blendergltf status to glTF 2.0

- README.md
- extensions/README.md
Changes:
- Avoid linking to draft extensions, if drafts are out of date.
- List KHR_materials_common under glTF 1.0 until updated otherwise. Fixes #1089.
- Move glTF 2.0 tools to top of the converters/exporters list.
- Remove older Unity Exporter, which doesn't appear to be the active one.
> Update docs on extensions, exporters, and converters.

- README.md
Finished most features of gltf 2 for the loader. Take off that 'geometry-only' hat.
> Update minimal-gltf-loader status

- README.md
Moves the Babylon and three.js viewers to a "~~Debugging~~" "Viewers and Debugging"  section, and adds a new [animation visualizer](https://bengfarrell.github.io/animation-visualizer/#) by @bengfarrell.
> Add debugging tools section.

- specification/2.0/README.md
In some parts of the documentation, it lists 5120 as being the component type for UNSIGNED_BYTE whereas elsewhere it lists 5121 as the component type.
> Mismatched component type for UNSIGNED_BYTE

- README.md
Have been tested on glTF2.0 models from [glTF Sample Models](https://github.com/KhronosGroup/glTF-Sample-Models) and [Sketchfab](https://sketchfab.com/features/gltf)
> Add qtek-model-viewer to viewers and debugging

- specification/2.0/README.md
- specification/2.0/schema/textureInfo.schema.json
> Add more restrictions on indexed attribute semantics

- README.md
`fbx2gltf` is a python tool for converting models to glTF2.0 format. It supports `FBX`, `COLLADA`, `OBJ` formats as input, thanks to the FBX SDK. And outputs `nodes`, `meshes`, `materials`, `animations`, `skins`. Morph target and binary glTF are not implemented yet.
Hope it can be an option in the toolchain :)
> Add fbx2gltf to converters

- extensions/Prefixes.md
Please add a "vendor extension prefix" for Alibaba.
[Hilo3d](https://github.com/hiloteam/Hilo3d) is a WebGL Rendering Engine developed by Alibaba Group.
> Add ALI extension prefix for Alibaba

- extensions/Khronos/KHR_technique_webgl/schema/shader.schema.json
- specification/1.0/schema/asset.schema.json
- specification/1.0/schema/buffer.schema.json
- specification/1.0/schema/image.schema.json
- specification/1.0/schema/shader.schema.json
Following the example set in glTF 2.0 by #838, this updates old glTF 1.0 URI formats from `uri` to `uriref`.  The same is done for `KHR_technique_webgl` for the same reason.
Additionally, the glTF 1.0 `asset.version` has gained a regex pattern-match such that it must begin with `1.`.  This is to make the schema "not match" any later versions.
Fixes #1149
/cc @lexaknyazev
> Update all remaining format:uri to format:uriref, tweak version 1.

- specification/2.0/README.md
- specification/2.0/schema/animation.sampler.schema.json
The working group last week agreed that Catmull-Rom should be removed from the spec. This is a PR to remove it. Let's discuss how to proceed.
> Remove Catmull-Rom spline from the specification

- specification/2.0/schema/animation.sampler.schema.json
Change JSON-Schema to allow rotation animation values to be provided as normalized integers. This is already the law of the land according to the spec's README.md & glTF-Validator.
Fixes https://github.com/KhronosGroup/glTF/issues/1183.
> Allow normalized integers for 'rotation' path

- README.md
I was just playing around with xeogl the other day and when I was looking at the WebGL engine list I notice it was marked as
> Added glTF 2.0 Status for xeogl

- README.md
As of today, jMonkeyEngine officially supports gltf2.0
https://github.com/jMonkeyEngine/jmonkeyengine/releases/tag/v3.2.0-stable
So I thought it would be nice it appears in the readme.
> Added jMonkeyEngine to the list of engines supporting glTF

- specification/2.0/README.md
There is not another instance of GL_FLOAT and think this was left behind or GL_ was accidentally added
> Removed GL_ prefix from GL_FLOAT in 2.0 spec

- README.md
Current link is pointing to a fork that hasn't been updated/maintained like the original repo
> Updated Rust Loader link to active repo

- specification/2.0/README.md
This PR fixes typo in the specification 2.0, removing an extra "with".
> Fix typo in the specification 2.0, remove an extra "with"

- README.md
Hi,
This pull request is about adding the [ClayGL](http://claygl.xyz/) to WebGL engines. And rename the old [QTEK Model Viewer](https://github.com/pissang/qtek-model-viewer) to the new [Clay Viewer](https://github.com/pissang/clay-viewer).
ClayGL is a WebGL library that published 1.0 in the last week. And Clay Viewer is built on top of it.
Here is an example of loading the Polly glTF Model with ClayGL.
http://examples.claygl.xyz/examples/basicGLTFCameraAnimation.html
> Add ClayGL to WebGL Engines. Rename QTEK Model Viewer to Clay Viewer

- specification/2.0/README.md
See #1177 
To support existing GLB implementations, this change clarifies that the BIN chunk of a binary glTF asset must be the second chunk for GLB version 2. If a need arises that requires a custom chunk between the JSON and BIN chunk, we will increment the GLB version.
> Clarify that GLB BIN chunk must be second

- extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md
`extensionRequired` replaced with `extensionsRequired`
`extensionUsed ` replaced with `extensionsUsed `
> typo fix in Draco README

- specification/2.0/README.md
In [image.uri section](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#imageuri) we see
> The image format must be jpg or png.
then I think I should remove "etc." from
> Image files (.jpg, .png, etc.) for textures
in [glTF Basics section](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#gltf-basics) for the consistency.
> Clean up image files format description

- extensions/2.0/Khronos/KHR_technique_webgl/README.md
> Update KHR_technique_webgl spec for missing bufferView references.

- extensions/2.0/Vendor/MSFT_lod/README.md
- extensions/2.0/Vendor/MSFT_lod/schema/glTF.MSFT_lod.schema.json
- extensions/2.0/Vendor/MSFT_packing_normalRoughnessMetallic/README.md
- extensions/2.0/Vendor/MSFT_packing_normalRoughnessMetallic/schema/glTF.MSFT_packing_normalRoughnessMetallic.schema.json
- extensions/2.0/Vendor/MSFT_packing_occlusionRoughnessMetallic/README.md
- extensions/2.0/Vendor/MSFT_packing_occlusionRoughnessMetallic/schema/glTF.MSFT_packing_occlusionRoughnessMetallic.schema.json
- extensions/2.0/Vendor/MSFT_texture_dds/README.md
- extensions/2.0/Vendor/MSFT_texture_dds/schema/glTF.MSFT_texture_dds.schema.json
- extensions/README.md
Merging these Microsoft specific extensions back into master so that they are more discoverable. 
There are some ongoing discussions for others adopting some of these like the LOD extension. If there is interest in that, a separate multi-vendor extension can be added. Wanted to get these is in so that there is good documentation/snapshot of what we are currently doing.
> Add MSFT vendor extensions 

- specification/2.0/README.md
This change adds an implementation note about how transforms of the root node of the skeleton hierarchy and the skinned mesh node affect the skinned mesh. The working group has been discussing this for a while now and it would great to get some feedback from the community.
For some background, the original issue came from the [Polly model](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) from the glTF Blender exporter. The eyelids were authored in a way that didn't work in some engines (e.g. Babylon.js).
> https://github.com/javagl/JglTF/issues/21#issuecomment-335064449
> [Babylon.js 33338](http://www.html5gamedevs.com/topic/33338-the-gltf-model-of-polly-does-not-animate-correctly/)
> Add implementation notes about which transforms apply to skinned meshes

- README.md
Hello, this adds another glTF 2.0 serialization/deserialization library to the mix. It is well tested by using the glTF-Sample-Models repo as well as project_polly etc.
> Add `fx-gltf` to the list of c++ tools

- extensions/2.0/Khronos/KHR_materials_unlit/README.md
- extensions/2.0/Khronos/KHR_materials_unlit/schema/glTF.KHR_materials_unlit.schema.json
- extensions/README.md
Updated version of #1095 as alternative to #1150 (KHR_materials_common).
> KHR_materials_unlit

- README.md
Added to readme exporter list.
**How to export**
Install `cqparts` with:
```bash
pip install cqparts
```
Then export `cube.step` -> `cube.gltf` & `cube.bin` (for example) with:
```python
from cqparts import Part
Part.importer('step')('cube.step').exporter('gltf')('cube.gltf')
```
**Docs**
gltf exporter class documentation: https://fragmuffin.github.io/cqparts/doc/api/cqparts.codec.html#cqparts.codec.gltf.GLTFExporter
**Example Output**
https://fragmuffin.github.io/cqparts/doc/tutorials/assembly.html
> added cqparts as exporter

- extensions/Prefixes.md
Closes #1349 
Also removes a duplicate space that my editor caught.
> Add MOZ prefix.

- specification/2.0/README.md
This PR incorporates feedback from #1086, #1096, and #1321.
Please confirm with implementations:
> All nodes listed in `scene.nodes` array must be the roots of trees in the node forest.
If it's true, no other action is needed (the validator has been checking for that since the beginning).
> Clarify node hierarchy terms

- specification/2.0/README.md
_Following up from https://github.com/KhronosGroup/glTF/issues/1252#issuecomment-395024604._
Should different `tangent.w` values be considered as a warning or an error?
> Add a note about tangent.w values

- README.md
I think Maya2glTF is mature enough to be featured on the readme page. It would also be helpful to show the 3DS Max and Maya exporters in the "Getting Started For Artists" section.
Thanks @j-conrad for pointing this out!
> Add Maya2glTF to exporter list and improve getting started for artists section

- README.md
As discussed in #1058, heading for the "Game Engines" section has been changed to "Game and Rendering Engines"
> Add Ogre_glTF plugin to the list

- extensions/Prefixes.md
This is for an upcoming vendor extension for AGI's desktop software, STK (Systems ToolKit).
Also, clean up wording about applying labels to issues.  Only the maintainers can adjust issue labels.
> Add the AGI prefix.

- README.md
Adds FME Desktop to list of gLTF Tools under "Converters, Importers, and Exporters" sub-section.
> FME Desktop

- extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
It looks like [the section on implementing the BRDF for specular glossiness material](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md) was copied from the metallic roughness. 
It says:
> The following equations show how to calculate bidirectional reflectance distribution function (BRDF) inputs (cdiff, F0, α) from the metallic-roughness material properties. 
But I assume that should say "specular-glossiness" instead? Does anything else need to change about the remainder of this paragraph for spec-gloss?
> Fix typo in spec-gloss spec

- README.md
Hilo3d glTF viewer is an online tool that previews the glTF models, supporting file dragging or links. It also can shares the model through links.
e.g.
* viewer: https://hiloteam.github.io/Hilo3d/examples/glTFViewer/index.html
* modelShare: https://hiloteam.github.io/Hilo3d/examples/glTFViewer/index.html?url=https://cx20.github.io/gltf-test/tutorialModels/Suzanne/glTF/Suzanne.gltf
> Add Hilo3d glTF viewer to viewers list

- specification/2.0/README.md
- specification/2.0/schema/material.normalTextureInfo.schema.json
In the section normalTextureInfo.scale, the formula is
```
scaledNormal =  normalize((normalize(<sampled normal texture value>) * 2.0 - 1.0) * vec3(<normal scale>, <normal scale>, 1.0))
```
But it's not correct. 
e.g.: 
1. Assume that the original normal value is  (0, -1, 0)
1. In the texture it will be (0.5, 0, 0.5)
1. After the normalize it will be (0.7071, 0, 0.7071)
1. Finally it will be (0.4142, -1, 0.4142)，obviously, this is wrong.
Should the code be 
```
normalize((normalize(<sampled normal texture value> * 2.0 - 1.0)) * vec3(<normal scale>, <normal scale>, 1.0))
```
or just remove the normalize
``` 
normalize((<sampled normal texture value> * 2.0 - 1.0) * vec3(<normal scale>, <normal scale>, 1.0))
```
> NormalTexture value should not be normalized

- specification/2.0/schema/accessor.schema.json
- specification/2.0/schema/accessor.sparse.indices.schema.json
- specification/2.0/schema/bufferView.schema.json
- specification/2.0/schema/mesh.primitive.schema.json
- specification/2.0/schema/sampler.schema.json
In [glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO) we are using [quicktype](https://github.com/quicktype/quicktype) to automatically generate python classes from the glTF JSON schema.
This commit adds explicit integer type specifiers to some enums, which prevents quicktype from wrongly deducing a type of float for these enum values ([refer to this warning in the JSON schema docs](https://json-schema.org/understanding-json-schema/reference/numeric.html#integer) for details).
> Add explicit type descriptor to integer enums

- README.md
Please consider adding **CAD Assistant** to convertors list.
The last release now exports CAD files into glTF2.0 (previously, glTF1.0 was exported).
> Add CAD Assistant to README.md

- extensions/2.0/Vendor/EXT_lights_image_based/schema/light.schema.json
- extensions/README.md
This is a follow-up to #1377.
None of our other extensions specify a long relative path in their schemas, so I've removed the path here for consistency.
Also, updated the README for the list of extensions.
> Remove path from EXT_lights_image_based schema, update README.

- extensions/2.0/Khronos/KHR_techniques_webgl/schema/technique.uniform.schema.json
The schema for `technique.uniform.schema.json` inherits from `glTFProperty` so it shouldn't have `name` property. Uniform names come from `technique.uniforms` keys.
> Remove `name` from technique.uniform

- README.md
I removed links to the old exporter and to julienduroure's old importer, and replaced them with a link to the new combined IO package.
/cc @donmccurdy
> README upgraded from Blender Exporter to Blender IO

- extensions/2.0/Vendor/EXT_lights_image_based/schema/glTF.EXT_lights_image_based.schema.json
- extensions/2.0/Vendor/EXT_lights_image_based/schema/light.schema.json
- extensions/2.0/Vendor/EXT_lights_image_based/schema/scene.EXT_lights_image_based.schema.json
- Addresses #1491 
- Updates for `specularImageSize`:
- description to match the spec;
- enforcing integer type;
- disallowing `0`.
Should we also disallow negative `intensity`?
> Small fixes for EXT_lights_image_based schemas

- specification/2.0/README.md
> Clarify naming of application-specific semantics in morph targets.

- extensions/2.0/Khronos/KHR_lights_punctual/schema/light.schema.json
This updates `KHR_lights_punctual` to use the same style of enums as the rest of the glTF schemas.  The new enum descriptions are just copy/paste from the main README.
/cc @donmccurdy @MiiBond
> Update KHR_lights_punctual to use glTF-style enum.

- README.md
Copied the style from the 2017 listing.
Also added VSCode (the app itself) to the app section, since it will auto-suggest the extension for install.
> Add SIGGRAPH 2018 BoF video

- README.md
README has almost no pure C loaders; this commit adds cgltf to the list which can be used to parse glTF 2.0 files.
> Add cgltf to README.md

- specification/2.0/README.md
Pretty much a copy-and-paste from https://github.com/KhronosGroup/glTF/issues/1028, to help explain that morph target scalar weights are all just concatenated together. If we wanted to be particularly fancy we could do some ASCII art.
> Clarify the structure of morph target weights

- specification/2.0/README.md
I'm not sure if that's a good example but it seems important to point out that `accessor.count` is incomplete for the size of the buffer
> Use a more complete example

- extensions/README.md
This is just to add the new `EXT_texture_webp` extension to the list of multi-vendor extensions.
> Add EXT_texture_webp to list of extensions

- extensions/2.0/Vendor/AGI_articulations/README.md
- extensions/2.0/Vendor/AGI_stk_metadata/README.md
- extensions/2.0/Vendor/EXT_texture_webp/README.md
* `EXT_texture_webp`
* `AGI_articulations`
* `AGI_stk_metadata`
These three extensions had status `Draft`, and should now be considered `Complete` as they have shipped (or soon be shipped) with production software.
/cc @OmarShehata
> Change three vendor extensions from "Draft" to "Complete"

- README.md
Adds a new section to `README.md` for formats built on glTF.
Following [the announced OGC and Khronos Liaison](https://www.khronos.org/news/press/ogc-and-khronos-form-a-liaison-to-improve-interoperability-within-the-geospatial-and-3d-graphics-communities), this seeks to promote glTF as standard foundation which can be referenced by other formats. To support that, should we include [Web3D's SRC format](http://www.web3d.org/src-and-gltf) and the [VRM format (still draft)](https://dwango.github.io/en/vrm/)?
> Add section to README.md for formats built on glTF

- README.md
qmuntal/gltf is a pure Go reader,writer and validator for glTF 2.0
> Add qmuntal/gltf to README.md

- specification/2.0/README.md
- specification/2.0/schema/node.schema.json
- specification/2.0/schema/skin.schema.json
Fixes #1383 and #1270. 
Before merging, "Property Reference" section of the spec needs to be updated as well.
> Add skinning clarifications

- specification/2.0/README.md
- specification/2.0/schema/texture.schema.json
> Explain why texture.source is not always required

- README.md
I knew these links existed somewhere, but I think it makes sense to gather them into the caption below the main overview card, for better discoverability.
via https://github.com/javagl/gltfOverview/issues/9
/cc @javagl
> Add links to PDF and other forms of reference cards

- extensions/2.0/Vendor/FB_geometry_metadata/README.md
- extensions/2.0/Vendor/FB_geometry_metadata/schema/scene.FB_geometry_metadata.schema.json
- extensions/2.0/Vendor/FB_geometry_metadata/schema/sceneBounds.schema.json
- extensions/2.0/Vendor/FB_geometry_metadata/schema/worldBounds.schema.json
This is a fairly rough write-up of an extension we use internally to provide some geometry-related summary information to parts of our system that can't or don't want to compute it themselves.
I'm not sure it has relevance for the rest of the world, but perhaps we can use this conversation thread to find out!
The schema files should be schematically valid JSON, but I'm not sure if they make semantic sense. In general, feedback is very welcome.
> FB_geometry_metadata extension

- README.md
Added [GLTFUtility](https://github.com/Siccity/GLTFUtility) under [Game and Rendering Engines](https://github.com/KhronosGroup/glTF#game-and-rendering-engines) as discussed in https://github.com/KhronosGroup/glTF/issues/1593
> Add GLTFUtility to readme

- README.md
This adds a more discoverable link to the sample viewer.  @donmccurdy had already updated the URLs, and this updates the descriptions.
> Add a more prominent link to the sample viewer

- extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
glossinessFactor's type must be "number", not "number[]"
> Fix a typo of README.md in KHR_materials_pbrSpecularGlossiness

- specification/2.0/README.md
The description of the output accessor was omitting the possibility that
rotation track is using normalized integers. This was fixed in #1187
however the change didn't propagate to the specification; the intention
is for the property reference to be generated but for now just fix it
directly.
Fixes #1622.
> Fix description of animation output accessor

- specification/2.0/README.md
Morph target names are not required to perform morphing. A real time application that consume glTF assets doesn't need morph target names in the general case. 
Rightly so, glTF doesn't impose assets to have target names, but it also doesn't provide a way to optionally add them.
It seems that, since the release of glTF 2.0 in mid-2017, a number of implementation (three.js, the official Blender exporter, UnityGLTF, a and at least one Maya exporter (and probably some others software, I haven't made a list, these are the few I'm aware of)).
This has been discussed in issue #1036. 
The goal is to help implementations that wants to do so have a way to do so in an interoperably way. Currently this has been done by adding a `targetNames` extras properties to the object.
Maybe a more proper way …
> Add non-normative note about the current usage of mesh.extras.targetNames

- README.md
Updates README to include [`trimesh`](https://github.com/mikedh/trimesh/) in a new Python language section. Trimesh can currently import all the models in the `sample-models 2.0` corpus, and can export to glTF or GLB.
> Update README to include trimesh

- specification/2.0/README.md
This makes it more explicit that buffers without a buffer.uri only refer
to BIN chunk when they are the first in the array; the behavior is left
undefined.
Fixes #1684.
> Clarify behavior of dummy buffers in GLB files

- extensions/README.md
Feedback welcome. If my suggested `<PREFIX>_<scope>_<feature>` structure is too prescriptive, I don't mind omitting it.
> Document naming convention for extensions

- extensions/2.0/Khronos/KHR_mesh_quantization/README.md
- extensions/2.0/Khronos/KHR_quantized_geometry/README.md
This is a draft of KHR_mesh_quantization (formerly known as KHR_quantized_geometry), that allows geometry attributes to use 8-bit and 16-bit types, which allows the encoders to choose the optimal tradeoff between quality and memory/transmission size.
The extension is specified to make implementations trivial; this is "de-facto" supported by Babylon.JS and Three.JS in that files that use 8/16-bit attributes can be deserialized by the respective loaders without further changes. I'd expect in general any compliant loader to be able to support this with minimal effort.
[Rendered version](https://github.com/KhronosGroup/glTF/blob/39bece7df9cf0b4a800afecfe78f179968ab87d3/extensions/2.0/Khronos/KHR_mesh_quantization/README.md) (updated 11/13)
Open questions:
- Is the number of possible …
> KHR_mesh_quantization

- extensions/Prefixes.md
For better transparency, I have updated the list of registered vendor prefixes with full company names (where applicable), websites, and contact information (when it was provided with the original request).
Also fixes #1732.
> Update prefixes list

- README.md
Hi, I have a python library for GLTF2 that people seem to like using, so thought I'd add it to your list. Hope it's useful and thanks for creating such an accessible and open format!
> add python library pygltflib to README.md

- extensions/README.md
Updates the various PBR next extensions (https://github.com/KhronosGroup/glTF/milestone/2), and removes extensions we aren't currently working on.
> Update extension status table.

- extensions/2.0/Khronos/KHR_lights_punctual/README.md
- extensions/2.0/Khronos/KHR_materials_clearcoat/README.md
- extensions/2.0/Khronos/KHR_materials_unlit/README.md
- extensions/2.0/Khronos/KHR_texture_transform/README.md
This is a copy/paste of the Khronos boilerplate copyright notice from the main glTF spec.  It's already in `KHR_draco_mesh_compression` and `KHR_techniques_webgl`, but was missing from some of the newer extensions.
> Add Khronos copyright text

- extensions/2.0/Khronos/KHR_materials_clearcoat/README.md
Fixed a word wrap issue, and tried to clarify the essence of what prompted the recent formula change.
> Tweak clearcoat wording & formatting a bit.

- extensions/Prefixes.md
I have a new physics extension in the works and have switched from using the BLENDER prefix to this new PANDA3D prefix.
> Add PANDA3D vendor prefix

- extensions/2.0/Khronos/KHR_materials_clearcoat/README.md
As pointed out by @rsahlin in https://github.com/KhronosGroup/glTF/pull/1688#discussion_r448262644, the parameter list is normative, and the implementation notes are non-normative.
Previously this extension had them mixed together without clear demarcation, so I've separated them here.
Also the trademark list at the bottom has been updated, copied from the new one in `KHR_xmp` that includes newer Khronos standards such as ANARI etc.
> Clearcoat: Better separation of non-normative section, update trademarks.

- extensions/2.0/Vendor/EXT_mesh_gpu_instancing/README.md
- extensions/2.0/Vendor/EXT_mesh_gpu_instancing/schema/glTF.EXT_mesh_gpu_instancing.schema.json
This change cleans up the spec and explicitly allows quantized
quaternions with types BYTE and SHORT.
Also add an implementation note suggesting that the base mesh should not
be rendered.
Fixes #1818.
> EXT_mesh_gpu_instancing: Allow quantized quaternions

- specification/2.0/README.md
> Clarify the restriction on accessor counts within a primitive

- extensions/2.0/Khronos/KHR_materials_transmission/README.md
I don't consider this a spec change so much as increased clarity, as this is a natural conclusion to draw from the physics. However, calling it out is important as it might not be obvious that IOR would affect the amount of roughness blur. 
I purposefully put "unless otherwise specified by another extension" because this will be handled differently when using the volume extension since at that point the transmission surface becomes single-sided (entering the volume).
> Added note about IOR and roughness for transmission

- extensions/2.0/Khronos/KHR_materials_variants/schema/glTF.KHR_materials_variants.schema.json
- extensions/2.0/Khronos/KHR_materials_variants/schema/mesh.primitive.KHR_materials_variants.schema.json
This is a technical update to align `KHR_materials_variants` schemas with the core glTF design principles.
- All objects should inherit from `glTFProperty`.
- `extras` and `extensions` need to be mentioned explicitly.
- Elements of a top-level array inherit from `glTFChildOfRootProperty`.
- Empty arrays are not allowed.
/cc @jercytryn @sleroux
> Align KHR_materials_variants schemas with the core spec

- specification/2.0/README.md
- specification/2.0/schema/bufferView.schema.json
- specification/2.0/schema/extras.schema.json
- specification/2.0/schema/material.schema.json
This PR manually cleans up some minor discrepancies that have separated the JSON schema from the generated reference section over the years.
I'd like to merge this first, in advance of re-running the automated conversion.  Running the automated conversion will break old URL hash references into the Markdown version, but those will break anyway when we migrate to AsciiDoctor, so we can save that for a later PR and get it all done in one shot.
> Manual cleanup to bring schema and reference into better alignment.

- specification/2.0/README.md
Following the discussion from https://github.com/KhronosGroup/glTF-Validator/issues/132.
Rationale is borrowed from https://github.com/KhronosGroup/glTF-Validator/pull/124#issuecomment-552758108 by @zeux.
/cc @vpenades
> Elaborate on skinning weights sum

- .gitignore
- specification/2.0/Makefile
- specification/2.0/Specification.adoc
@oddhack This is a PR into your branch, to add the JSON schema file contents.
via https://github.com/CesiumGS/wetzel/pull/51
> Add JSON schemas to AsciiDoctor output.

- extensions/2.0/Khronos/KHR_texture_basisu/README.md
- extensions/README.md
These were both ratified on November 20, 2020.
> Update Extensions README to mark sheen & basisu as ratified

- specification/2.0/Makefile
- specification/2.0/Specification.adoc
This modifies the Asciidoctor HTML & PDF specs to compare asciidoctor latexmath rendering vs. the image approaches previously used. See the
generated HTML / PDF in the Actions artifacts download and search for
"Latexmath" (followed by "Old") versions of each equation.
Relevant points:
* The HTML output is not self-contained. It introduces an external dependency on the MathJax package on a CDN outside our control.
* MathJax runs after the HTML page is loaded and takes noticeable time - initially you will see the raw latex markup, replaced and re-laid-out with the formatted math.
* The PDF output introduces a new dependency on the asciidoctor-mathematical gem (the Khronos Docker image already has this).
* The PDF math rendering quality is noticeably lower than the HTML rendering quality.
> Compare latexmath to image math rendering in asciidoctor branch

- README.md
Seems like a relevant addition here? Wouldn't generally list third-party extensions as formats, but I think this is sufficiently notable, and has its own ecosystem and file extension.
> Add VRM to "Formats Built on glTF"

- specification/2.0/Specification.adoc
Sectioned all hanging text by creating an initial sub-section with the text from the parent. The end result is a document with all text in a specific section. No section contains sub-sections and text.
1. New subsection for main sections (_X_. _name_) are _X_.1 General
1. Other new subsections (_X.Y..._. _name_) are _X.Y..._.1 Overview
1. New anchor is created for each new sub-section by appending _-general_ or _-overview_ to the parent label
> Sectioned hanging text

- specification/2.0/Specification.adoc
This moves the copyright up top, and puts all credits at the end.  Neil requested this on a recent call.
> Flip credits & copyrights

- extensions/2.0/Khronos/KHR_materials_variants/README.md
Looking over the contributor list for the KHR_material_variants, we forgot to include Mikko who worked on the spec and also built the prototype viewer. This PR adds him to the contributor list.
> Add missing contributor for KHR_materials_variants extension

- extensions/2.0/Khronos/KHR_materials_variants/schema/glTF.KHR_materials_variants.schema.json
- extensions/2.0/Khronos/KHR_materials_variants/schema/mesh.primitive.KHR_materials_variants.schema.json
I'm not a fan of this, as I'd rather see all "extras" everywhere get tightened to be an object, rather than the lone object get loosened to be "any".  But the former is too big a breaking change to be considered for glTF 2.0, and conformance will help the glTF Validator enforce uniform behavior, so here we are.
For https://github.com/KhronosGroup/glTF-Validator/issues/149#issuecomment-739353647
One question though, is this change itself too big a breaking change for a released extension?
/cc @lexaknyazev @bghgary @jercytryn
> Material Variants: Modify "extras" to use same convention as elsewhere in glTF.

- extensions/2.0/Khronos/KHR_materials_transmission/README.md
Fix sample code for the KHR_materials_transmission extension as discussed in the issue #1924
> Fixed sample code in KHR_materials_transmission extension specification

- README.md
When the README.md is imported to Khronos.org/gltf, although the links don't appear on the khronos.org/gltf landing page, they are in the source, and produce a 404 error for search engines. Converting the links to absolute resolves this issue. 
This PR is a 'nice to have', not required to approve.
> Convert links README links from relative to absolute

- extensions/2.0/Vendor/EXT_meshopt_compression/README.md
This extension is now supported by gltfpack on the tooling side and by Three.js, Babylon.js on the renderer side, with additional support in cgltf (which is a parsing library).
Since no issues came up during implementation for these libraries, it would make sense to mark the extension as complete.
> Mark EXT_meshopt_compression as complete

- extensions/2.0/Khronos/KHR_texture_basisu/README.md
Fixes #1934.
This update future-proofs the extension for material textures that may intentionally use fewer than three color channels.
> Clarify R and RG textures handling

- extensions/2.0/Khronos/KHR_materials_ior/README.md
- extensions/2.0/Khronos/KHR_materials_ior/schema/glTF.KHR_materials_ior.schema.json
An extension for the metallic-roughness material that makes the index of refraction configurable. At the moment, there is a fixed value of 1.5, corresponding to F0 = 0.04.
This extension is similar to KHR_materials_specular proposed in #1677, but should work better in combination with KHR_materials_transmission (#1698). It allows to set IOR>2, which is not uncommon for transparent materials.
The extension uses some notation introduced in #1717.
> KHR_materials_ior

- extensions/2.0/Khronos/KHR_materials_variants/README.md
KHR_materials_variants currently restricts both variant and material index to be unique within each mapping
It makes sense that the variant index must be used no more than one time - duplicate indices would create ambiguity.
However, the specification should restrict the duplicate occurrence of materials.
Per #1937, mappings are represented as objects to allow for application extensibility - to specify data with extras.
The restriction above maintains that an application must use the same extras data for any two variants that happen to have an identical material (or duplicate the material).
This is overly restrictive; if the extras data contains variant/mesh-specific annotations, this data doesn't have to match between different variants even if they use the same material.
This change …
> KHR_materials_variants: Relax index uniqueness restrictions

- specification/2.0/Specification.adoc
- specification/2.0/schema/accessor.schema.json
- specification/2.0/schema/accessor.sparse.indices.schema.json
- specification/2.0/schema/accessor.sparse.schema.json
- specification/2.0/schema/accessor.sparse.values.schema.json
- specification/2.0/schema/animation.sampler.schema.json
- specification/2.0/schema/animation.schema.json
- specification/2.0/schema/asset.schema.json
- specification/2.0/schema/buffer.schema.json
- specification/2.0/schema/bufferView.schema.json
- specification/2.0/schema/camera.orthographic.schema.json
- specification/2.0/schema/camera.perspective.schema.json
- specification/2.0/schema/camera.schema.json
- specification/2.0/schema/extension.schema.json
- specification/2.0/schema/extras.schema.json
- specification/2.0/schema/glTF.schema.json
- specification/2.0/schema/image.schema.json
- specification/2.0/schema/material.normalTextureInfo.schema.json
- specification/2.0/schema/material.occlusionTextureInfo.schema.json
- specification/2.0/schema/material.pbrMetallicRoughness.schema.json
- specification/2.0/schema/material.schema.json
- specification/2.0/schema/mesh.primitive.schema.json
- specification/2.0/schema/mesh.schema.json
- specification/2.0/schema/node.schema.json
- specification/2.0/schema/sampler.schema.json
- specification/2.0/schema/skin.schema.json
- specification/2.0/schema/texture.schema.json
- specification/2.0/schema/textureInfo.schema.json
* Use BCP 14 normative language.
* Properly list all external references.
* Expand the Samplers section.
* Expand material texture descriptions.
* Reduce emphasis on OpenGL.
* Minor language edits.
* Restrict certain PNG and JPEG variations.
* Full rewrite of JSON encoding section, relaxing some of previously-unenforced restrictions.
* Explicitly allow IRIs.
* Explicitly disallow `bufferView.byteStride` for buffer views that do not contain vertex attributes.
* Elaborate on image media types handling.
* Restore accidentally removed vertex color usage.
* Discourage use of zero-length GLB BIN chunks.
> Update normative language

- specification/2.0/README.md
@WestLangley noticed that for our suggested implementation, if you plug in a pure dielectric material at normal incidence, our equations reduce to `f_diffuse = (1 / pi) * (1 - f0)^2 * baseColor`, which seems to be an error, as the energy-conservation term `(1 - f0)` is double-counted. I believe this is the right fix, but would appreciate more eyes on it.
> removed duplicate (1 - f0) in implementation notes

- extensions/2.0/Khronos/KHR_texture_basisu/README.md
- extensions/2.0/Khronos/KHR_texture_transform/README.md
[PlayCanvas v1.46.0](https://github.com/playcanvas/engine/releases/tag/v1.46.0) adds support for both `KHR_texture_basisu` and `KHR_texture_transform` glTF 2.0 extensions. This PR adds the engine to both extensions' lists of implementations.
> Add PlayCanvas to KHR_texture_basisu and KHR_texture_transform

- extensions/2.0/Khronos/KHR_xmp_json_ld/README.md
This is in preparation of sending off `KHR_xmp_json_ld` to the board for re-ratification to a non-provisional status.
Changes:
* Updated all references of `ISO/DIS 16684-3` to `ISO 16684-3`.
* Updated copyright dates to include 2021.
> Updates for KHR_xmp_json_ld

- specification/2.0/Specification.adoc
- specification/2.0/schema/accessor.schema.json
- specification/2.0/schema/animation.channel.target.schema.json
- specification/2.0/schema/asset.schema.json
- specification/2.0/schema/mesh.schema.json
- specification/2.0/schema/node.schema.json
- Clarified Points and Lines rendering.
- More detailed explanation of sampler wrapping modes.
- Reordered and expanded skinning section.
- Added examples of non-ASCII paths.
- Removed the reference to the external extension document (it will be replaced anyway).
- Added references to GL-originated integer enum values. 
- Minor tweaks, language and typography fixes.
> Integrate latest AsciiDoc updates

- extensions/2.0/Vendor/EXT_meshopt_compression/README.md
To make sure that the spec for EXT_meshopt_compression is actually implementable, I've worked with @magcius to create a reference JS decoder by following the spec, and validate it using decoding tests from the original implementation.
While not a perfect clean-room implementation (the original implementation had to be consulted a couple of times because the spec was difficult to understand), this seems sufficiently comprehensive to make sure that the spec actually describes the intended bitstream correctly.
During this process, two bugs in the spec were found, both of them in the octahedral filter:
- fixed point encoding of 1.0 was stored in the .Z element ([2]); the comment correctly pointed that out, but pseudo-code used index 3
- the octahedral transform used the wrong sign (+= …
> Update EXT_meshopt_compression specification to fix and clarify bitstream format

- specification/2.0/README.md
Addressing https://github.com/KhronosGroup/glTF/issues/2036 . For a preview of the updated readme, see https://github.com/KhronosGroup/glTF/blob/b4484b3b01272ddfb170dbadb64976c9c784db1b/specification/2.0/README.md
> Added hint about preview of AsciiDoc file

- specification/2.0/Specification.adoc
Fixes https://github.com/KhronosGroup/glTF/issues/1637.
The updated language implies that when an extension has its own normal texture, another set of tangents may need to be generated. This does not require indexing tangent attributes because the generation happens only when they are missing completely.
/cc @donmccurdy
> Clarify MikkTSpace texture coordinates

- specification/2.0/Specification.adoc
This adds preview-only warning notes to the two auto-generated sections, providing links to the fully-rendered versions, and an instruction about how to suggest changes.
Also the conditional was changed from `ifdef::env-github[]`, which is GitHub-specific, to `ifndef::revdate[]` which is specific to the glTF doc build process.  This means the notes will be visible to many more previewers in addition to GitHub, such as VSCode's adoc preview window.
There should be no change to the final rendered output from this PR.  (I diffed the outputs to check).
> Add preview-mode-only warnings around auto-generated sections.

- specification/2.0/Makefile
This adds little hoverable anchor symbols to the left of each heading, for easy linking.  Copied from Vulkan Docs.
Also updated comment about docker image source, it has changed since it was first written.
> Add section anchors (copied from Vulkan Docs)

- specification/2.0/Specification.adoc
Minor language refinements:
- use "transformation" only with "matrix", consistently use "transform" otherwise;
- better view matrix description.
> Adjust transform descriptions

- specification/2.0/Specification.adoc
Following conversation from https://github.com/KhronosGroup/glTF/issues/1314#issuecomment-754820704 and subsequent comments, I'd like to add an implementation note encouraging optimizations for zero-scale meshes.
Zero-scale meshes can be used to animate visibility of a mesh, and can enable use-cases such as fluid simulation where the computed mesh changes shape and changes number of vertices over a set of known timesteps.
/cc @donmccurdy @javagl
> Add note about zero-scale meshes.

- specification/2.0/Specification.adoc
- specification/2.0/schema/material.schema.json
> Clarify A2C applicability

- extensions/README.md
I noticed the "thinfilm" extension branch has been closed and apparently replaced by an "iridescence" branch.
> Fix link / extension name for in-progress KHR extension

- extensions/2.0/Khronos/KHR_materials_volume/README.md
For `thicknessFactor`, `thicknessTexture`, and `attenuationDistance`, the intervals given in the specification either don't match the schema, or don't seem correct based on context. I've updated them to match the schema and added the range in interval notation within the Properties table.
> KHR_materials_volume: Corrections to intervals of volumetric properties

- extensions/2.0/Khronos/KHR_materials_specular/README.md
In #2022 the duplicate (1-F0) term was removed from `c_diff` in the core spec. This PR removes it also from the KHR_material_specular extension.
> Remove duplicate 1-max(F0.rgb) in KHR_materials_specular

- extensions/2.0/Archived/KHR_materials_pbrSpecularGlossiness/README.md
- extensions/2.0/Archived/KHR_techniques_webgl/README.md
- extensions/2.0/Khronos/KHR_materials_clearcoat/README.md
- extensions/2.0/Khronos/KHR_materials_ior/README.md
- extensions/2.0/Khronos/KHR_materials_sheen/README.md
- extensions/2.0/Khronos/KHR_materials_specular/README.md
- extensions/2.0/Khronos/KHR_materials_transmission/README.md
- extensions/2.0/Khronos/KHR_materials_unlit/README.md
- extensions/2.0/Vendor/ADOBE_materials_clearcoat_specular/README.md
- extensions/2.0/Vendor/ADOBE_materials_thin_transparency/README.md
- extensions/2.0/Vendor/EXT_lights_image_based/README.md
This fixes a number of spec links to use the glTF registry.
(/cc @MiiBond this touches some ADOBE extensions too).
> Update many spec links

- extensions/2.0/Khronos/KHR_xmp_json_ld/README.md
- extensions/README.md
Apparently I forgot to submit this PR in October after the `KHR_xmp_json_ld` extension became fully ratified by the Khronos Board of Directors. This corrects that mistake.
> Marked KHR_xmp_json_ld as ratified

- extensions/2.0/Khronos/KHR_materials_transmission/README.md
- extensions/2.0/Khronos/KHR_materials_volume/README.md
[Github added support for Latex math in Markdown](https://github.blog/2022-05-19-math-support-in-markdown/). This PR replaces the `<img>` tags by `$` and `$$`.
> Use Github Markdown math for equations

- extensions/Prefixes.md
As mentioned in https://github.com/KhronosGroup/glTF/pull/2209#discussion_r988238495 , most root URLs in the prefixes list did have trailing slashes `/`, but some didn't. This PR adds them where they have not been present.
> Consistently add trailing slash to root URLs

- extensions/2.0/Vendor/EXT_lights_image_based/README.md
- extensions/2.0/Vendor/MSFT_lod/README.md
- extensions/2.0/Vendor/MSFT_packing_normalRoughnessMetallic/README.md
- extensions/2.0/Vendor/MSFT_packing_occlusionRoughnessMetallic/README.md
- extensions/2.0/Vendor/MSFT_texture_dds/README.md
> Add license info to Microsoft extensions

- extensions/2.0/Khronos/KHR_materials_transmission/README.md
Typo. Fixes https://github.com/KhronosGroup/glTF/issues/2234.
> Update KHR_materials_transmission, blendMode → alphaMode

- extensions/2.0/Vendor/EXT_meshopt_compression/README.md
Attempt to use filters on time values may reduce precision more than appropriate; in the past, glTF-Transform erroneously used 12-bit mantissas with exponential filter, which isn't enough for sub-millisecond precision on animation keys.
Exponential encoding with 23-bit mantissa results in ~10% smaller time tracks with minimal precision loss, but the time track is normally insignificantly small anyway so this note recommends either approach.
Fixes #2119
> EXT_meshopt_compression: Add a note about animation inputs (time)

- extensions/2.0/Khronos/KHR_materials_transmission/README.md
This is a minor fix to an implementation note in the KHR_materials_transmission extension. I believe there's a missing negative sign in our computation for the transmission half vector (must use dot(N,-L)).
This is already done correctly in the sample viewer: [punctional.glsl](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/9693a0380cd268f18e7523a3e2b961cda58b3c02/source/Renderer/shaders/punctual.glsl#L83)
I also confirmed that EnterprisePBR also uses the correct dot(N,-L). See equation 5 in [EnterprisePBR](https://dassaultsystemes-technology.github.io/EnterprisePBRShadingModel/spec-2022x.md.html#components/core/dielectricbsdffortransparentsurfaces)
> KHR_materials_transmission: Minor fix to implementation note.

- extensions/2.0/Khronos/KHR_materials_anisotropy/schema/glTF.KHR_materials_anisotropy.schema.json
The "detailed description" for strength had accidentally been placed in the ordinary JSON description property.  I moved it where it should have been, in `gltf_detailedDescription` like the other long descriptions.
This does not change the REAMDE, or behavior, and has no IP changes for ratification.
> Anisotropy strength: Fix choice of JSON schema field

- extensions/2.0/Vendor/NV_materials_mdl/README.md
This was an oversight when changing `type.schema.json` to `functionCall.type.schema.json`.
> Fix wrong schema link in NV_materials_mdl

- extensions/Prefixes.md
I got married some time ago and took the lastname of my wife, so the email is not correct anymore :)
> chore: change name of ALCM vendor prefix contact

- extensions/2.0/Khronos/KHR_materials_anisotropy/README.md
- extensions/2.0/Vendor/EXT_mesh_gpu_instancing/README.md
- extensions/2.0/Vendor/EXT_meshopt_compression/README.md
- extensions/2.0/Vendor/EXT_texture_webp/README.md
- extensions/README.md
The following extensions have been ratified this year:
- KHR_materials_anisotropy
- EXT_mesh_gpu_instancing
- EXT_meshopt_compression
- EXT_texture_webp
Additionally, some wording was adjusted to allow EXT extensions to become ratified, and to clarify when _required_ status should be marked on an extension.
(Also, some links to glTF 1.0 extensions removed. Anyone who needs those should click on the relevant folder, no need to advertise them anymore).
> Mark several recently ratified extensions as complete, update registry

- extensions/2.0/Khronos/KHR_draco_mesh_compression/schema/mesh.primitive.KHR_draco_mesh_compression.schema.json
- extensions/2.0/Khronos/KHR_lights_punctual/schema/glTF.KHR_lights_punctual.schema.json
- extensions/2.0/Khronos/KHR_lights_punctual/schema/light.schema.json
- extensions/2.0/Khronos/KHR_lights_punctual/schema/light.spot.schema.json
- extensions/2.0/Khronos/KHR_lights_punctual/schema/node.KHR_lights_punctual.schema.json
- extensions/2.0/Khronos/KHR_materials_anisotropy/schema/glTF.KHR_materials_anisotropy.schema.json
- extensions/2.0/Khronos/KHR_materials_clearcoat/schema/glTF.KHR_materials_clearcoat.schema.json
- extensions/2.0/Khronos/KHR_materials_emissive_strength/schema/glTF.KHR_materials_emissive_strength.schema.json
- extensions/2.0/Khronos/KHR_materials_ior/schema/glTF.KHR_materials_ior.schema.json
- extensions/2.0/Khronos/KHR_materials_iridescence/schema/glTF.KHR_materials_iridescence.schema.json
- extensions/2.0/Khronos/KHR_materials_sheen/schema/glTF.KHR_materials_sheen.schema.json
- extensions/2.0/Khronos/KHR_materials_specular/schema/glTF.KHR_materials_specular.schema.json
- extensions/2.0/Khronos/KHR_materials_transmission/schema/glTF.KHR_materials_transmission.schema.json
- extensions/2.0/Khronos/KHR_materials_unlit/schema/glTF.KHR_materials_unlit.schema.json
- extensions/2.0/Khronos/KHR_materials_variants/schema/glTF.KHR_materials_variants.schema.json
- extensions/2.0/Khronos/KHR_materials_variants/schema/mesh.primitive.KHR_materials_variants.schema.json
- extensions/2.0/Khronos/KHR_materials_volume/schema/glTF.KHR_materials_volume.schema.json
- extensions/2.0/Khronos/KHR_texture_basisu/schema/texture.KHR_texture_basisu.schema.json
- extensions/2.0/Khronos/KHR_texture_transform/schema/KHR_texture_transform.textureInfo.schema.json
- extensions/2.0/Khronos/KHR_xmp_json_ld/schema/KHR_xmp_json_ld.schema.json
- extensions/2.0/Khronos/KHR_xmp_json_ld/schema/glTF.KHR_xmp_json_ld.schema.json
This PR improves the schema titles. This is mostly cosmetic, but it may have practical benefits, such as improved human and machine parsability, and it gives us the ability to uniquely identify a schema file from its title alone.
When making this PR, I used the following rules:
* All titles should be in Title Case where words start with a capital letter except for stylized `glTF`.
* All extension schemas should include the extension name at the start. For example, all `KHR_lights_punctual` schemas should start the title with "KHR_lights_punctual".
* Previously the light properties schema was just titled `"light"`. This is not unique enough to be helpful without the context of knowing you are dealing with `KHR_lights_punctual`.
* Schemas that extend a specific part of glTF should specify …
> Use friendly unique names for all Khronos extension schemas

- extensions/2.0/Vendor/FB_geometry_metadata/README.md
Corrects the extension property name and content description.
> Fix apparent FB_geometry_metadata copy-paste typo

- extensions/2.0/Khronos/KHR_materials_anisotropy/README.md
This exclusion note is present in every single material extension except for this one. I assume this is an omission since it's not clear why anisotropy specifically would be okay to mix with unlit and every other KHR_materials_ extension isn't.
Note that other material extensions also say it's not okay to mix them with `KHR_materials_pbrSpecularGlossiness`. I did not add this exclusion for now to reduce the scope of the change but let me know if that is preferred here as well.
If we don't end up adding this exclusion I feel like we should explicitly clarify the opposite.
> KHR_materials_anisotropy should be exclusive vs unlit

- extensions/2.0/Vendor/EXT_mesh_manifold/README.md
Sorry, I just realized I forgot to update the status of the extension before we merged it.
> EXT_mesh_manifold: update draft to complete

- extensions/2.0/Khronos/KHR_materials_iridescence/README.md
This PR fixes two issues:
1. Math rendering seems to be broken because of missing 'githubusercontent' images. I replaced the the images with actual latex math.
2. Use correct cosine for optical path difference calculation as reported in #2212
> Fix iridescence math

- extensions/2.0/Vendor/GRIFFEL_bim_data/schema/GRIFFEL_bim_data.schema.json
Fixes https://github.com/KhronosGroup/glTF/issues/2373 :
The [item](https://github.com/KhronosGroup/glTF/blob/ae1a90baf009203760304f06ed5645402de9dc09/extensions/2.0/Vendor/GRIFFEL_bim_data/schema/GRIFFEL_bim_data.schema.json#L20) property should have been called items.
> Fix `GRIFFEL_bim_data` extension schema

- extensions/2.0/Vendor/GRIFFEL_bim_data/schema/glTF.GRIFFEL_bim_data.schema.json
Fixes #2373
There was another instance of the `item` property inside of an array instance type, which should have been `items`. (`item` is not a known property in json schema draft 4)
> Additional fix to `GRIFFEL_bim_data` extension schema

- extensions/2.0/Vendor/CESIUM_primitive_outline/schema/primitive.CESIUM_primitive_outline.schema.json
When I wrote the schema for this extension, I incorrectly used `integer` as the type for the `indices` property, which is meant to refer to an accessor in the glTF. It should instead be `"allOf": [ { "$ref" : "glTFid.schema.json" } ]`.
> Fix type of CESIUM_primitive_outline's `indices` property.

- extensions/README.md
Updates naming in the extensions/README.md list from `KHR_materials_sss` to `KHR_materials_subsurface`, following https://github.com/KhronosGroup/glTF/pull/1928.
> Update reference to "KHR_materials_subsurface" in README.md

- extensions/2.0/Khronos/KHR_materials_clearcoat/README.md
- extensions/2.0/Khronos/KHR_materials_ior/README.md
- extensions/2.0/Khronos/KHR_materials_sheen/README.md
- extensions/2.0/Khronos/KHR_materials_specular/README.md
- extensions/2.0/Khronos/KHR_materials_transmission/README.md
- specification/2.0/Specification.adoc
This PR fixes the bug with the squared metallic term in the reference BRDF implementation in Appendix B by rewriting the pseudocode according to the proposal of @lisyarus. In addition, all extensions referencing the code are updated.
Besides, I removed a few inconsistencies in the extensions:
* Snake case is now consistently used for values in the implementation, and camelCase for public parameters.
* BRDFs are now called `xxx_brdf` instead of a mixture between `f_xxx` and `xxx_brdf`.
* The clearcoat extension now differentiates more clearly between clearcoat normal (Nc) and material normal (N)
* The visibility term is now referred to as $\mathcal{V}$ to distinguish it from the view direction $V$.
* The specular extension now uses the same structure for factor * color multiplications as …
> Fix reference BRDF implementation (#2386)

- extensions/2.0/Khronos/KHR_materials_sheen/README.md
- extensions/2.0/Khronos/KHR_materials_transmission/README.md
- specification/2.0/Specification.adoc
This is a simple search-and-replace of `\mathcal{V}` with `\nu` as a fix for the PDF render issue in #2401.
@bsdorra @proog128 Any objection to changing the letter like this?
> Fix missing glyph

- extensions/Prefixes.md
Following https://github.com/KhronosGroup/glTF-Validator/pull/218
> Remove obsolete reference to the validator's old list of prefixes

- extensions/2.0/Khronos/KHR_materials_anisotropy/README.md
- extensions/2.0/Khronos/KHR_materials_anisotropy/schema/material.KHR_materials_anisotropy.schema.json
> Update anisotropy extension spec

- extensions/2.0/Khronos/KHR_materials_volume/README.md
Fixes #2390
Based on comments in https://github.com/KhronosGroup/glTF/issues/2390#issuecomment-2158480643
Related sample viewer PR: https://github.com/KhronosGroup/glTF-Sample-Viewer/pull/550
> Clarify and simplify formula for attenuation

- extensions/2.0/Khronos/KHR_materials_clearcoat/README.md
> Update clearcoat extension spec

- extensions/README.md
Add KHR_node_hoverability after KHR_node_visibility
> Add KHR_node_hoverability

- README.md
As there is a lot more traffic to the Khronos glTF Discord than there is to Slack, a button pointing users to Discord will be helpful.
> Add button/link to glTF Discord

- README.md
Follow-up from https://github.com/javagl/gltfOverview/pull/11
> Add link to Chinese version of overview

- extensions/2.0/Vendor/EXT_texture_webp/README.md
- extensions/2.0/Vendor/EXT_texture_webp/schema/glTF.EXT_texture_webp.schema.json
Editorial updates; the most important is the proper upstream reference since WebP has an official RFC document now.
> EXT_texture_webp: Editorial updates

- extensions/2.0/Khronos/KHR_lights_punctual/README.md
In #2214 I ended up also making explicit the presumed separation between light intensity and light colour. (I.E. Light colour does not get normalized to match the intensity.) I also did some minor grammar and formatting changes/fixes.
This `cherry-pick`s those changes.
This is not meant to change what the specification says, only make clearer and explicit what I believed was already presumed.
> `KHR_lights_punctual`: Clarify relationship between intensity and color. Also some grammar.

- specification/2.0/ObjectModel.adoc
This update ensures that applications can query asset's nodes structure and material references.
> Update read-only object model pointers

- extensions/2.0/Vendor/EXT_meshopt_compression/README.md
Looking at [`meshopt_encodeFilterOct`](https://github.com/zeux/meshoptimizer/blob/20b26f98746a439600b20065a69ab0c66c4cca5c/src/vertexfilter.cpp#L877) as a reference, the bit range should be `1 <= K <= 16`, not `4 <= K <= 16`.
@zeux does this change look correct?
> Fix K-bits range for meshopt octahedral filter
