converter/COLLADA2GLTF/COLLADA2GLTFWriter.cpp
converter/COLLADA2GLTF/GLTF/GLTFAsset.cpp
converter/COLLADA2GLTF/GLTFOpenCOLLADAUtils.cpp
converter/COLLADA2GLTF/GLTFOpenCOLLADAUtils.h
converter/COLLADA2GLTF/shaders/commonProfileShaders.cpp

Fall back to A_ONE whenever the glTF converter doesn't know how to handle other COLLADA opaqueMode(s)

Fix issue 350

---

specification/techniquePassStates.schema.json

Minor spec fixes

---

converter/COLLADA2GLTF/GLTF/GLTFAsset.cpp
converter/COLLADA2GLTF/GLTF/GLTFConfig.cpp
converter/COLLADA2GLTF/GLTF/GLTFWriter.cpp
converter/COLLADA2GLTF/GLTF/GLTFWriter.h
converter/COLLADA2GLTF/main.cpp

As-is, this changes the default behavior to ugly-print and allows enabling pretty-print. Not sure whether that should change. @tfili

Add option to output minified glTF JSON

---

specification/schema/accessor.schema.json
specification/schema/animationChannel.schema.json
specification/schema/animationParameter.schema.json
specification/schema/animationSampler.schema.json
specification/schema/buffer.schema.json
specification/schema/bufferView.schema.json
specification/schema/cameraPerspective.schema.json
specification/schema/glTF.schema.json
specification/schema/glTFChildOfRootProperty.schema.json
specification/schema/image.schema.json
specification/schema/lightAmbient.schema.json
specification/schema/lightDirectional.schema.json
specification/schema/lightPoint.schema.json
specification/schema/lightSpot.schema.json
specification/schema/meshPrimitive.schema.json
specification/schema/node.schema.json
specification/schema/sampler.schema.json
specification/schema/shader.schema.json
specification/schema/skin.schema.json
specification/schema/technique.schema.json
specification/schema/techniqueParameters.schema.json
specification/schema/techniqueStates.schema.json
specification/schema/texture.schema.json

This is a pull request into `spec-1.0`.
The corresponding commit to wetzel is [cf95016b144212bed90abf3607d0d61e52b52117](https://github.com/AnalyticalGraphicsInc/wetzel/commit/cf95016b144212bed90abf3607d0d61e52b52117).

Added detailed description properties to schema

---

specification/README.md
specification/schema/accessor.schema.json
specification/schema/animation.channel.schema.json
specification/schema/animation.channel.target.schema.json
specification/schema/animation.parameter.schema.json
specification/schema/animation.sampler.schema.json
specification/schema/animation.schema.json
specification/schema/bufferView.schema.json
specification/schema/camera.schema.json
specification/schema/glTF.schema.json
specification/schema/material.schema.json
specification/schema/mesh.primitive.attribute.schema.json
specification/schema/mesh.primitive.schema.json
specification/schema/node.schema.json
specification/schema/program.schema.json
specification/schema/scene.schema.json
specification/schema/skin.schema.json
specification/schema/technique.attribute.schema.json
specification/schema/technique.parameters.schema.json
specification/schema/technique.schema.json
specification/schema/technique.states.functions.schema.json
specification/schema/technique.uniform.schema.json
specification/schema/texture.schema.json

From @slchow.
This is a pull request into `spec-1.0`.

Spec 1.0 copyedits

---

specification/README.md

Closes #430.
Merging into `spec-1.0`.

Minor spec tweaks

---

COLLADA2GLTF/GLTF/GLTFEffect.cpp

Fixed build issue

---

README.md

@FuzzyWuzzie thanks for developing haxe-gltf!  We added it to our list of glTF-related tools and apps.  Please keep us updated on your progress.

Added haxe-gltf to README.md

---

README.md

Organizes the loader section of README.md by language.
Adds links to awesome work by @syoyo and @ksons.

Add Tiny glTF loader and gltf-walker

---

README.md

Thanks to @kimkulling and @otgerp!

Add Assimp to README.md

---

README.md

Promising tool by @Qantas94Heavy!

Add link to binary-gltf-utils

---

README.md
specification/README.md

@tparisi for your review and merge

Add Khronos Trademark Statement

---

COLLADA2GLTF/GLTF/GLTFEffect.cpp

Removed the type/value setup for KHR_materials_common values. It should just be the value.

Updated converter to newest KHR_materials_common spec

---

specification/README.md

@tparisi for your review.  This is a small fix to an example in the spec.

Replace old aspect_ratio example with aspectRatio

---

README.md

Add PEX glTF loader to README.md

---

README.md

Add xeoEngine to README.md

---

README.md

Add FBX to/from glTF talk

---

COLLADA2GLTF/COLLADA2GLTFWriter.cpp
COLLADA2GLTF/GLTF/GLTFTypesAndConstants.h

@fabrobinet did this in #343, but it looks like it never made it into master.
Also related to #556.

"aspect_ratio" should be "aspectRatio"

---

COLLADA2GLTF/CMakeLists.txt
COLLADA2GLTF/COLLADA2GLTFWriter.cpp
COLLADA2GLTF/GLTF/GLTFAnimation.cpp
COLLADA2GLTF/GLTF/GLTFAsset.cpp
COLLADA2GLTF/GLTF/GLTFAsset.h
COLLADA2GLTF/GLTF/GLTFMesh.cpp
COLLADA2GLTF/convert/animationConverter.h
COLLADA2GLTF/convert/meshConverter.cpp
COLLADA2GLTF/extensions/o3dgc-compression/GLTF-Open3DGC.cpp
COLLADA2GLTF/extensions/o3dgc-compression/GLTF-Open3DGC.h
COLLADA2GLTF/helpers/geometryHelpers.cpp
COLLADA2GLTF/main.cpp
COLLADA2GLTF/shaders/commonProfileShaders.cpp

For #199 
Fixed trivial warnings. Still need to fix four more `C4503` warnings.

Fixed warnings when building

---

COLLADA2GLTF/GLTF/GLTFAsset.cpp

Fixes #584 by checking if TEXCOORD is bound to a technique

Fix for #584

---

README.md

Add aframe-gltf to README.md

---

COLLADA2GLTF/COLLADA2GLTFWriter.cpp

There were some test failures in an AGI project dependent on COLLADA2GLTF after my last change: #595. 
While largely cosmetic, it is still better to only create new mesh instances if they are necessary, so this change checks if the bound material is an instance first.
I have run this change against that AGI project and the tests all pass, and @gbeatty's box model with instance materials on each side also converts correctly, so this should be good to go.

Only make unique mesh instances if the material is an instance

---

extensions/README.md

This should have been in #600.

Move KHR_binary_glTF to non-draft section

---

specification/README.md
specification/schema/technique.parameters.schema.json

As discussed in https://github.com/KhronosGroup/glTF/issues/563#issuecomment-223122123

Clarify that parameter.node does not allow some semantics

---

specification/README.md

Remove unused parts of the Default Material example in Appendix A

---

specification/README.md

Update EXT_binary_glTF reference to use KHR_ prefix

---

specification/schema/examples/extensions.json

For https://github.com/KhronosGroup/glTF/issues/563#issuecomment-218509248

Clarify extension example

---

specification/README.md
specification/schema/accessor.schema.json

For https://github.com/KhronosGroup/glTF/issues/593#issuecomment-223636136
@lexaknyazev what do you think?

More specific constraints for accessor min and max

---

COLLADA2GLTF/COLLADA2GLTFWriter.cpp

Fixes a few problems with #595 on AGI models

More robust detection of mesh instances

---

extensions/Vendor/WEB3D_quantized_attributes/README.md
extensions/Vendor/WEB3D_quantized_attributes/schema/WEB3D_quantized_attributes.accessor.schema.json

For #610 and #588 
@pjcozzi @mlimper

Updated quantized attributes extensions

---

sampleModels/README.md

@pjcozzi I missed this in that last pull request

Fixed image path and BrainStem name

---

specification/README.md
specification/schema/technique.parameters.schema.json

For https://github.com/KhronosGroup/glTF/issues/563#issuecomment-210993081
@lexaknyazev what do you think of this clarification?

Clarify that array parameters are not the same as vectors

---

specification/README.md
specification/schema/buffer.schema.json

Removed "text" form buffer.type.

---

specification/README.md

Clarify usage of buffer.type

---

sampleModels/BrainStem/README.md

@lasalvavida Follow-up to #626.

Corrected EULA link, now points to most recent version

---

specification/README.md
specification/schema/node.schema.json
specification/schema/skin.schema.json

small fixes for #624, add skinning attributes definitions from glTF Overview

Small skinning fixes

---

specification/README.md
specification/schema/glTF.schema.json
specification/schema/mesh.primitive.schema.json
specification/schema/mesh.schema.json

See #639.
Also added a note about uint indices.

Mandatory dictionaries

---

extensions/Khronos/KHR_binary_glTF/README.md

Fix MIME type

---

COLLADA2GLTF/COLLADA2GLTFWriter.cpp
COLLADA2GLTF/GLTF/GLTFAccessor.cpp
COLLADA2GLTF/GLTF/GLTFAccessor.h
COLLADA2GLTF/GLTF/GLTFAnimation.cpp
COLLADA2GLTF/GLTF/GLTFAsset.cpp
COLLADA2GLTF/GLTF/GLTFTypesAndConstants.h
COLLADA2GLTF/extensions/o3dgc-compression/GLTF-Open3DGC.cpp
COLLADA2GLTF/profiles/webgl-1.0/GLTFWebGL_1_0_Profile.cpp

Part of the changes for #659.
@tfili Could you look at this when you get a chance?

min and max are generated for all accessors

---

extensions/Vendor/WEB3D_quantized_attributes/README.md

@mlimper are you OK with these additions?

Add links to WEB3D_quantized_attributes  extension

---

README.md

Added Cinder WIP

---

README.md

Added GLBoost to README.md

---

specification/README.md

Add clarification on texture origin.

---

specification/README.md
specification/schema/accessor.schema.json

Add accessor.normalized

---

specification/README.md
specification/schema/arrayValues.schema.json
specification/schema/material.values.schema.json
specification/schema/technique.parameters.schema.json

Make technique.parameter.value always array

---

specification/README.md
specification/schema/accessor.schema.json

https://github.com/KhronosGroup/glTF/issues/344#issuecomment-245332052

Сlarify normalized usage

---

specification/README.md
specification/schema/technique.states.functions.schema.json

Align blendColor and depthRange parameters with WebGL spec

---

specification/README.md

Remove obsolete "count" property from animations example

---

specification/README.md
specification/schema/node.schema.json

Clarify TRS order

---

README.md

Thanks to @KermMartian!
Fixes #714

Added gltf2glb to README.md

---

README.md

Add link to Stack Overflow

---

COLLADA2GLTF/COLLADA2GLTFWriter.cpp

@tfili, this should fix our issue as discussed offline.

Clone transformations so OpenCOLLADA can't free memory we're using

---

loaders/dummy/glTF-parser.js

Several changes here, but the functional change is updating the data URI regex to be case-insensitive.
I've also cleaned up the resolvePathIfNeeded function to not rely on a separate, private function, not require a match (which is more expensive than a test), and added some commenting and considerations for future improvements.

Fix data URI detection to be case-insensitive.

---

README.md

Added "Bringing 3D to everyone through open standards" article

---

README.md

Added "glTF Brief for W3C Workshop" article

---

specification/README.md

Fixes https://github.com/KhronosGroup/glTF/issues/766

Default material values should be contained in technique

---

specification/README.md

Fix typo in spec.

---

README.md

Added model-tag to README.md

---

README.md

Thanks to @Alteous.
@kainino0x this may interest you.

Added glTF Rust library to README.md

---

specification/1.0/schema/asset.schema.json

This pull request updates asset.schema.json for schema 0.4 consistency.

Update schema definition asset for schema 0.4 consistency.

---

README.md

I would like to add yocto-gltf to the C++ library list.

Added yocto-gltf to the C++ library list.

---

README.md

Added alembic_to_gltf and cyhair_to_gltf to README.md

---

README.md

Thanks to @cedricpinson and crew.

Added Sketchfab to README.md

---

README.md

Added Archilogic to README.md

---

README.md

Thanks to @DavidPeicho @cedricpinson

Added OSG.JS to list of engines that support glTF

---

README.md

Added link to WordPress glTF plugin

---

README.md

Add glTF Webinar to README.md

---

README.md

Add Laugh Engine to README.md

---

README.md

Add WebGL-PBR to README.md

---

specification/2.0/schema/textureInfoBase.schema.json

Generalize textureInfoBase.index and restrict textureInfoBase.texCoord

---

extensions/Prefixes.md

Add BLENDER extension prefix

---

specification/2.0/schema/buffer.schema.json

glTF 2.0 buffer.uri should not be a required property

---

README.md

Add entry for `gltf-vscode`, also add headings for editors and comparison.
There is also a [tweet announcing this](https://twitter.com/emackey/status/844203957564166145) with a little demo in a gif.

Add gltf-vscode

---

specification/2.0/schema/material.normalTextureInfo.schema.json
specification/2.0/schema/material.occlusionTextureInfo.schema.json
specification/2.0/schema/material.pbrMetallicRoughness.schema.json
specification/2.0/schema/material.schema.json

1) Update packing info for metal roughness texture #857
2) Add formulas for occlusion strength #884 and normal scale #885

Update metal-roughness texture packing

---

specification/2.0/README.md
specification/2.0/schema/bufferView.schema.json

As discussed offline.
CC @sbtron @bghgary @pjcozzi

Refine bufferView.target

---

specification/2.0/README.md
specification/2.0/schema/image.schema.json
specification/2.0/schema/sampler.schema.json
specification/2.0/schema/texture.schema.json

@bghgary @sbtron 
Please review refined schemas. If everything's OK, I'll update readme and merge asap.

Yet another glTF 2.0 texture updates

---

specification/2.0/README.md

First pass on property reference generated from JSON schema.
Contains description update from #901 
Please review to find any issues with generated md.

Add property reference

---

extensions/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
extensions/Khronos/KHR_materials_pbrSpecularGlossiness/schema/glTF.KHR_materials_pbrSpecularGlossiness.schema.json

Remove epsilon similar to Metal Roughness core spec
Allow additional properties similar to core spec

cleanup to match core spec

---

README.md

Added link to three.js drag-and-drop glTF viewer

---

README.md

Added link to BabylonJS Sandbox

---

specification/2.0/schema/buffer.schema.json
specification/2.0/schema/bufferView.schema.json

Adjust Buffer/BufferView byteLength/byteOffset

---

specification/2.0/schema/material.normalTextureInfo.schema.json
specification/2.0/schema/material.occlusionTextureInfo.schema.json
specification/2.0/schema/material.pbrMetallicRoughness.schema.json
specification/2.0/schema/textureInfo.schema.json

glTFProperty inheritance

---

specification/2.0/schema/accessor.schema.json

Require bufferView for byteOffset

---

specification/2.0/README.md
specification/2.0/schema/accessor.schema.json
specification/2.0/schema/animation.sampler.schema.json
specification/2.0/schema/node.schema.json

Refine morph.weights schema, allow normalized values

---

specification/2.0/schema/node.schema.json
specification/2.0/schema/scene.schema.json
specification/2.0/schema/skin.schema.json

Disallow empty arrays

---

README.md

This PR adds a new link to a cesium based glTF viewer.

Add gltf viewer link

---

extensions/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
specification/2.0/README.md

Adding explanation on how pbr materials properties interact with vertex colors if they are present.

Update vertex color calculation for metal-roughness and spec-gloss

---

specification/2.0/schema/node.schema.json

No spec changes, just JSON-Schema tightening.

Disallow presence of TRS and matrix at the same time

---

README.md

As requested in https://github.com/KhronosGroup/glTF/issues/456#issuecomment-302443243

Adds <gltf-viewer> to the list of viewers

---

specification/2.0/README.md

As mentioned in the telco, added the negative z-axis as default.

glTF 2.0: Added default setting for camera.

---

README.md

Could you add Redcube.js to "Loaders and Viewers" section?
Thank you.

add redcube.js to viewers

---

specification/2.0/README.md

Addresses comment from https://github.com/KhronosGroup/glTF-Sample-Models/pull/58#issuecomment-301198676

Clarify morph target attribute types, wording, and example

---

specification/2.0/schema/animation.channel.target.schema.json

To maintain forward-compatibility.

Future-proof animation.channel.target

---

specification/2.0/schema/camera.schema.json

Disallow ambiguous camera definition

---

extensions/Khronos/KHR_materials_pbrSpecularGlossiness/schema/glTF.KHR_materials_pbrSpecularGlossiness.schema.json

KHR_materials_pbrSpecularGlossiness extends glTFProperty.

---

specification/2.0/README.md

Clarify state of non-animated properties

---

README.md

Add link to glTF 2.0: PBR Materials talk

---

specification/2.0/README.md

No schema/conformance/validation changes. Just a clarification on expected client behavior.

Add couple notes on image.mimeType

---

specification/2.0/README.md

And added myself to the contributors

Add implementation note for lighting on LINES and POINTS

---

specification/2.0/README.md

Regenerated reference based on latest Wetzel and schema

Regenerated property reference

---

specification/2.0/README.md

Clarify matrix accessor alignment

---

specification/2.0/README.md
specification/2.0/schema/material.schema.json

Add normal map unpacking formula to normal map description

---

specification/2.0/README.md

From https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/16.

Fix UV origin

---

specification/2.0/README.md

See https://github.com/KhronosGroup/glTF/issues/995#issuecomment-306928016.

Elaborate on matrix data alignment

---

extensions/Prefixes.md

Added AVR prefix for AltspaceVR extensions

---

extensions/Khronos/KHR_technique_webgl/README.md

PR for #868,
it looks like the schema already allows this

Shader bufferView README changes

---

README.md

Add link to "Exporting glTF 2.0 from Maya LT" article

---

specification/2.0/README.md

Add note about identifying joint nodes.

---

README.md

The repo moved to an official Khronos repo.

Update link for glTF-WebGL-PBR

---

README.md

via @kimkulling
https://twitter.com/kimkulling/status/891284853425143809

Update assimp to glTF 2.0

---

specification/2.0/README.md

Manually fix properties reference to make glTF.asset required

---

README.md

Add links to Sketchup import and export

---

README.md

Add link to Physically-Based Rendering in Cesium article

---

README.md

Add link to "glTF Exporter in three.js and A-Frame" article

---

extensions/Prefixes.md

Add OWLII vendor extension prefix

---

specification/2.0/README.md

Add exporter implementation note about non-linear time inputs

---

README.md

Add link to Seattle Khronos Group Meetup slides

---

extensions/Prefixes.md

Add Google vendor extension prefix

---

specification/2.0/README.md
specification/2.0/schema/sampler.schema.json

Hint that S means U and T means V in wrapping modes

---

specification/2.0/README.md

Describe BIN chunk and buffer.byteLength relations

---

extensions/Vendor/CESIUM_RTC/README.md

Fix link in CESIUM_RTC

---

extensions/Prefixes.md

See https://github.com/KhronosGroup/glTF/pull/1137#issuecomment-340733432
CC @msfeldstein

Add FB extension prefix for Facebook

---

README.md

Add makeglb to list of optimizers

Add makeglb

---

README.md

https://medium.com/@donmccurdy/creating-animated-gltf-characters-with-mixamo-and-blender-728dc120e678

Adding "Creating animated glTF Characters..." post.

---

extensions/Prefixes.md

Add MSFT vendor prefix

---

README.md

Also rearranging order so that 2.0 tools are on top.

Add gltf-import-export npm package

---

specification/2.0/README.md

I think these words in the sparse accessor section just got a little jumbled at some point.

Tiny language tweak.

---

README.md

glTF C++ serializer/deserializer

Add Microsoft.glTF.CPP

---

README.md

Add GLTFSceneKit to README.md (Languages - Swift)

Add GLTFSceneKit to README.md

---

README.md

Nice article by @joshmarinacci

Add link to "Using glTF Models with A-Frame"

---

README.md

Add simplygon and gltf-toolkit

---

extensions/Khronos/KHR_materials_pbrSpecularGlossiness/README.md

Fixes https://github.com/KhronosGroup/glTF/issues/1185

Update example material values in KHR_materials_pbrSpecularGlossiness extension

---

README.md

Fixed Archilogic status to glTF 1.0

---

README.md

also added the jgltf-validator

fixed broken jgltf links

---

specification/2.0/README.md

As discussed and requested here https://github.com/KhronosGroup/glTF/issues/1108

Added clarification about regular nodes in a joint hierarchy

---

README.md

Add link to 'Art Pipeline for glTF'

---

specification/2.0/README.md
specification/2.0/schema/material.schema.json

Add info about normalizing normals

---

extensions/Prefixes.md

Add NVIDIA vendor extension prefix

---

extensions/Prefixes.md

Add AMZN vendor extension prefix for Amazon

---

extensions/Prefixes.md

Add Soft8Soft vendor extension prefix

---

extensions/Prefixes.md

Add Sketchfab vendor extension prefix

---

README.md

Add link to "Convert FBX format to glTF format on Blender and animate it with Three.js" article

---

specification/2.0/README.md

Added Max Limper to the working group section for his 2.0 spec work

---

README.md

Added Facebook to the Applications section!

---

extensions/README.md

Fix broken link

---

README.md

Pulled in what I had time to review from https://github.com/KhronosGroup/glTF/issues/1058, and added checkmarks by the ones included here.

Update applications, adoption, tools.

---

specification/2.0/README.md

See https://github.com/bghgary/glTF-Asset-Generator/issues/384#issuecomment-374677255

Clarify data alignment of vertex attributes

---

README.md

@bghgary could you also please open a PR to add your slides for your GDC meetup presentation on the asset generator?

Add links to GDC talks

---

specification/2.0/README.md

Add non-normative section for point/line materials.

---

README.md

Add a new Blender Importer link

Update README.md --> Add a Blender Importer

---

specification/2.0/README.md

Describe clamping before/after sampler input range

---

specification/2.0/README.md

Refine JSON encoding section

---

specification/2.0/README.md

Clarify accessor.count for morph targets

---

specification/2.0/README.md

Change position to translation in skin section

---

README.md

Add link to "Why glTF 2.0 is awesome!"

---

README.md

Add glTF-Generator-Registry to README.md.

---

extensions/Prefixes.md

Add LLQ prefix, and a node about updating the validator.

---

README.md

Add link to glTF 2.0 – Status and Outlook

---

README.md

glTFShowcase is Android APP for viewing gltf asset in Android devices.

Add "glTFShowcase" link to Viewer list

---

README.md

The sharp sign was not present.

C sharp typo in contents

---

extensions/Prefixes.md

Add ADOBE vendor extension prefix

---

specification/2.0/README.md

Add a note about no POSITION data

---

README.md

As was advised here
https://github.com/KhronosGroup/glTF/issues/456#issuecomment-420621965

Added UModel reference and description to Exporters section

---

README.md

https://github.com/jing-interactive/MeshViewer

README.md - add MeshViewer

---

specification/2.0/README.md

Update compression note.

---

specification/2.0/README.md

Add implementation note about key/value extras.

---

specification/2.0/README.md

Per #1142.
/cc @MiiBond @bghgary @lexaknyazev @emackey

Disallow primitive restart values.

---

extensions/2.0/Vendor/EXT_lights_image_based/schema/light.schema.json

Fix an issue with IBL rotation schema.

---

README.md

Add link to Adobe Dimensions blog post

---

specification/2.0/README.md

Add a note about URI normalization

---

specification/2.0/README.md

Add a note about binary buffer size

---

specification/2.0/README.md
specification/2.0/schema/bufferView.schema.json

Reword buffer.byteLength

---

specification/2.0/README.md

Tighten requirements for semantic names.

---

README.md

Thanks @pjcozzi for the pointer
Preview here: https://github.com/mlimper/glTF

Added RapidCompact to list of converters / optimizers

---

README.md

Masterpiece by @bghgary!  Perhaps the first glTF article of 2019.

Add link to "glTF Debugging in Visual Studio Code"

---

README.md

update README.md WebGL Engines - RedGL

---

extensions/2.0/Khronos/KHR_techniques_webgl/README.md
extensions/2.0/Khronos/KHR_techniques_webgl/examples/sample_techniques.gltf

> 
MODELVIEWINVERSETRANSPOSE | FLOAT_MAT3 | The inverse-transpose of MODELVIEW without the translation. This transforms normals in model coordinates to eye coordinates.
-- | -- | --

u_normalMatrix's type should be mat3

---

specification/2.0/README.md

Add info about unused joints for skinned mesh

---

README.md

Replace chat links with Slack channel.

---

README.md

Update glTFShowcase description to include iOS version.

Update glTFShowcase viewer description

---

README.md

Update WebGL Engines - Ashes

---

extensions/Prefixes.md

Add AGT prefix

---

extensions/2.0/Khronos/KHR_draco_mesh_compression/schema/node.KHR_draco_mesh_compression.schema.json
extensions/README.md

Fixes #1491.
- Updated Draco extension schema.
- Updated extension examples and guidelines.

Update extensions docs

---

specification/2.0/README.md

Rephrased the spec a bit and updated Property Reference.

Continuation of #1552

---

extensions/Template.md

I don't know if people use this template, or if they just grab a ratified extension and modify that, but if there's to be a template, it should be up-to-date...

Update the extension template to glTF 2.0?

---

extensions/2.0/Vendor/EXT_texture_webp/README.md

Minor update based on internal evaluation.
/cc @OmarShehata

Update WebP best practices

---

README.md

Added link to "glTF: Everything You Need to Know!" article

---

README.md

Adding Animate in exporters list and a blog

Updated Readme: Adding Animate as exporter and a blog

---

extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/schema/glTF.KHR_materials_pbrSpecularGlossiness.schema.json
specification/2.0/README.md
specification/2.0/schema/material.pbrMetallicRoughness.schema.json
specification/2.0/schema/material.schema.json

This PR makes color space descriptions more sound. No implementation changes.
Fixes #1280.

Reword colorspace descriptions

---

README.md

Also replace broken URL (404) to implementation ticket
Change-Id: I3f66e0d7f2f72c510d3475e459c41d8f61140006
Signed-off-by: Philippe Coval <p.coval@samsung.com>

tools: Update Archilogic support to glTF-2

---

README.md

Request to add JglTF-mesh https://github.com/chadj2/jgltf-mesh/

Add JglTF-mesh reference

---

extensions/Prefixes.md

Add SKYLINE vendor extension prefix

---

extensions/README.md

Note that I'm marking `KHR_blend` and `KHR_techniques_webgl` as "tabled", to indicate they aren't current priorities but could be picked up again at some point in the future. Other suggestions welcome!
/cc @lexaknyazev @bghgary

Update in-progress extensions list.

---

extensions/Prefixes.md

Add FX extension prefix for Foxit Software

---

extensions/Prefixes.md

Per comments in https://github.com/KhronosGroup/glTF/issues/1712#issuecomment-560141066

Update prefix "FX" to "FOXIT"

---

README.md

Hi!
as author of glTFast I'd be very glad to have it added to this list.
Thanks for consideration!

Added glTFast to the list of tools/libs for glTF.

---

extensions/Prefixes.md

@jjcasmar Your KDAB prefix should be registered.  Does this entry look OK?

Register KDAB prefix

---

README.md

Added Datakit CrossCad/Ware SDK in C++ tools

Added Datakit CrossCad/Ware SDK

---

extensions/Prefixes.md

Add MPEG prefix registration

---

README.md

Added Gestaltor to applications.

---

specification/2.0/appendix/performance-metrics/README.md

Formatting the JSON data, so the README is more legible.  Fix names vertexCount, nodeCount.

Format/Indent JSON data

---

extensions/Prefixes.md

Added TRYON vendor prefix

---

extensions/Prefixes.md

Add SPECTRUM vendor prefix

---

README.md

Details are added as comment at https://github.com/KhronosGroup/glTF-Project-Explorer/issues/37

Project list migration

---

README.md

Add link to "View a glTF model in AR on Android without leaving your browser"

---

specification/2.0/README.md

Based on https://github.com/KhronosGroup/glTF/issues/915 and https://github.com/KhronosGroup/glTF/issues/1427. 
Another change may still be needed after this, for the second part of https://github.com/KhronosGroup/glTF/issues/915#issuecomment-574413797.

Clarify that AO does not affect direct lighting.

---

extensions/Prefixes.md

Add SEIN vendor extension prefix

---

extensions/Prefixes.md

Add PTC prefix.

---

extensions/Prefixes.md

Add GRIFFEL prefix

---

extensions/Prefixes.md

Add MAXAR prefix

---

README.md

This was recorded in February, just pre-pandemic, and published in April.

Add glTF Model Authoring Pipeline series to README

---

specification/2.0/README.md

Fixes #944.
Thanks for the ping, @akien-mga.
See also: https://www.iana.org/assignments/media-types/application/gltf-buffer

Add application/gltf-buffer MIME type

---

specification/2.0/schema/material.schema.json

Remove comparison to GL coordinates in normalTexture schema.

---

extensions/2.0/Khronos/KHR_xmp/README.md
extensions/2.0/Khronos/KHR_xmp/schema/examples/xmp.gltf

As discussed, I've added a notice to the existing KHR_xmp extension specification indicating that a potential new version is under development. ~We can add a link to the new PR once I have opened it; hopefully later today but maybe tomorrow afternoon.~

Add review and new version notice to KHR_xmp

---

extensions/Prefixes.md

Add EPIC extension prefix

---

extensions/Prefixes.md

Add CLO prefix

---

extensions/2.0/Khronos/KHR_mesh_quantization/README.md

See https://github.com/mrdoob/three.js/issues/21553.
/cc @zeux

Add a note on dequantizing accessor bounds

---

extensions/Prefixes.md

Add OFT vendor extension.

---

extensions/README.md

Update extension listing for IOR, specular, and volume.

---

extensions/2.0/Khronos/KHR_materials_sheen/README.md

Fixes https://github.com/KhronosGroup/glTF/issues/1987

Fix incorrect info in contributor list

---

extensions/Prefixes.md

Add ASOBO prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/1962.

Add CITRUS vendor prefix.

---

extensions/Prefixes.md

Add OMI prefix

---

specification/2.0/Makefile

Add the **MUST** keyword to wetzel's output

---

specification/2.0/Specification.adoc
specification/2.0/schema/material.schema.json

@emackey 
Could you please update pre-defined strings in `wetzel` (and publish a new version to npm) so that they use `**MUST**` instead of `must`?

More language updates

---

extensions/2.0/Khronos/KHR_materials_transmission/README.md

Fix step function in visibility term of transmission extension.

---

specification/2.0/Specification.adoc

See https://github.com/KhronosGroup/glTF/issues/915#issuecomment-772593047.

Refine occlusion texture description

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1547.

Refine scenes introduction

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1860.

Refine accessors introduction

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1793.

Refine sparse accessors introduction

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1823.

Add node global transform definition

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1646.

Clarify the morph displacements order

---

specification/2.0/Specification.adoc

Follow-up as suggested in https://github.com/KhronosGroup/glTF/pull/2042#issuecomment-929602789.

Improve global transform language

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1603.

Clarify generated tangent space for morph targets

---

specification/2.0/Specification.adoc

Fixes https://github.com/KhronosGroup/glTF/issues/1461.

Update TANGENT attribute description

---

specification/2.0/schema/animation.channel.schema.json
specification/2.0/schema/animation.channel.target.schema.json
specification/2.0/schema/animation.sampler.schema.json
specification/2.0/schema/animation.schema.json

Update animation descriptions

---

specification/2.0/Specification.adoc

Clarify omitting morphed attributes

---

specification/2.0/Specification.adoc

Clarify position units

---

specification/2.0/Specification.adoc

Clarify camera parameters

---

CONTRIBUTING.adoc
specification/2.0/README.md

This should offer more guidance to those seeking to make corrections.
New version: [README.md](https://github.com/KhronosGroup/glTF/blob/bec27241a2082bbec2ae4f884357d19a2cfa91c8/specification/2.0/README.md)
/cc @javagl @lexaknyazev

Expand the README with instructions for contributing & building

---

specification/2.0/Specification.adoc

Most of these were found by Google Docs, and refined by me.

Spelling & article tweaks

---

specification/2.0/Specification.adoc

Provides full reference for all three interpolation modes and also fixes #1395.
/cc @scurest

Expand animation sampler interpolation section

---

extensions/Prefixes.md

Add EMBARK prefix

---

extensions/2.0/Khronos/KHR_materials_transmission/README.md

Fixes #2100.
The 2020x version does not seem to exist.

Fix link in KHR_materials_transmission

---

extensions/2.0/Khronos/KHR_xmp_json_ld/README.md

Corrections to minor typos and possibly unclear phrasing.

Minor corrections in KHR_xmp_json_ld/README.md

---

extensions/Prefixes.md

Add SHAPEDIVER extension prefix

---

extensions/Prefixes.md

Add OTOY prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2126
Fixes https://github.com/KhronosGroup/glTF/issues/2125
@lexaknyazev There is a statement
> Once a prefix is approved, it should be added to the [glTF Validator's list of known prefixes](https://github.com/KhronosGroup/glTF-Validator/blob/master/lib/src/ext/extensions.dart).
in the `Prefixes.md`. Should that just be a plain PR into the validator repository, or is there any further process required for "approving" a prefix?

Added MX and SNAP vendor prefixes

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2118
Fixes https://github.com/KhronosGroup/glTF/issues/2131
Fixes https://github.com/KhronosGroup/glTF/issues/2134

Added NEEDLE, SE, and TENCENT prefixes

---

extensions/2.0/Khronos/KHR_materials_emissive_strength/README.md

@emackey I'd be happy to be on that list. Thanks!

fix: Added myself as contributor to KHR_materials_emissive_strength

---

extensions/Prefixes.md

Add INTEL prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2150

Add MTTR vendor prefix

---

extensions/Prefixes.md

Add USSF prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2183 
Fixes https://github.com/KhronosGroup/glTF/issues/2185

Add HEVOLUS and UNITY extension prefixes

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2192

Add DOTV prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2204

Add ESSILORLUXOTTICA prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2206

Add VSEKAI prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2208

Add ICOSA prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2222

Add MAGNUM prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2230
Fixes https://github.com/KhronosGroup/glTF/issues/2231

Add MIRROR and AUDACES prefixes

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2240

Add GODOT prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2259

Add BENTLEY prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2264

Add C3D prefix

---

specification/2.0/Specification.adoc

This sentence is missing a verb. Added "be" to fix this.

Fix grammar mistake in Skins section

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2303

Add DGG prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2299

Add WGE prefix

---

extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md

- Fixes https://github.com/KhronosGroup/glTF/issues/2248

Refresh non-normative resource links for KHR_draco_mesh_compression

---

extensions/2.0/Vendor/EXT_meshopt_compression/README.md

clarify dummy buffer length

---

specification/2.0/ObjectModel.adoc

This is a prerequisite for the animation pointer and interactivity extensions.

Draft of the glTF Asset Object Model

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2344

Add KITTYCAD prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2363

Add ENVOKE prefix

---

extensions/2.0/Khronos/KHR_animation_pointer/README.md
extensions/2.0/Khronos/KHR_materials_dispersion/README.md
extensions/README.md

These two extensions were ratified at today's Board meeting.  Neil notified the 3D Formats WG via email a couple hours ago.

Mark Animation Pointer and Dispersion as ratified

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2398

Add MANYFOLD prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2416

Add TRACE prefix

---

extensions/2.0/Khronos/KHR_texture_procedurals/schema/material.KHR_texture_procedurals_schema.json

"multioutout" --> "multioutput"

Fix typo in "multioutput"

---

.github/workflows/CI.yml

See
- https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update GitHub Actions

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2445

Add MODUPLAY prefix

---

extensions/2.0/Khronos/KHR_materials_ior/README.md

KHR_materials_ior: Clarify zero value operation

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2469

Add SIRADEL prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2247 (there have not been further comments, but this PR should be reasonable to get this closed)

Update MPEG prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2497

Add BEVY prefix

---

extensions/Prefixes.md

Fixes https://github.com/KhronosGroup/glTF/issues/2523

Add MF prefix
